export const ENVIRONMENTAL_NICHES = [
  // Energías Renovables (20)
  { id: 'solar-residencial', name_es: 'Paneles Solares Residenciales', icon: '☀️' },
  { id: 'solar-comercial', name_es: 'Parques Solares Comerciales', icon: '☀️' },
  { id: 'eolica-marina', name_es: 'Energía Eólica Marina', icon: '🌬️' },
  { id: 'eolica-terrestre', name_es: 'Turbinas Eólicas Terrestres', icon: '🌬️' },
  { id: 'biomasa', name_es: 'Generación de Energía por Biomasa', icon: '🔥' },
  { id: 'hidroelectrica-micro', name_es: 'Micro-Hidroeléctricas', icon: '💧' },
  { id: 'geotermia', name_es: 'Sistemas de Geotermia', icon: '🌋' },
  { id: 'energia-undimotriz', name_es: 'Energía Undimotriz (Olas)', icon: '🌊' },
  { id: 'baterias-sostenibles', name_es: 'Baterías Libres de Cobalto', icon: '🔋' },
  { id: 'redes-inteligentes', name_es: 'Smart Grids Renovables', icon: '⚡' },
  { id: 'hidrogeno-verde', name_es: 'Producción de Hidrógeno Verde', icon: '🧪' },
  { id: 'biogas-urbano', name_es: 'Plantas de Biogás Urbano', icon: '♻️' },
  { id: 'solar-termal', name_es: 'Calentadores Solares Térmicos', icon: '🌡️' },
  { id: 'energia-mareomotriz', name_es: 'Energía Mareomotriz', icon: '🌊' },
  { id: 'perovskitas', name_es: 'Células Solares de Perovskita', icon: '✨' },
  { id: 'comunidades-energeticas', name_es: 'Comunidades Solares Compartidas', icon: '🏘️' },
  { id: 'piezoelectricidad', name_es: 'Baldosas Piezoeléctricas', icon: '🚶' },
  { id: 'carga-vehicular', name_es: 'Estaciones de Carga 100% Solar', icon: '🔌' },
  { id: 'software-solar', name_es: 'Software de Optimización Solar', icon: '💻' },
  { id: 'almacenamiento-termico', name_es: 'Almacenamiento Térmico en Arena', icon: '🏜️' },

  // Gestión de Residuos (20)
  { id: 'compostaje-industrial', name_es: 'Compostaje Industrial', icon: '🍂' },
  { id: 'compostaje-domestico', name_es: 'Suscripción de Compostaje Local', icon: '🪱' },
  { id: 'residuos-electronicos', name_es: 'Minería de Residuos Electrónicos', icon: '📱' },
  { id: 'gestion-baterias', name_es: 'Reciclaje de Baterías de Litio', icon: '🔋' },
  { id: 'escombros', name_es: 'Reutilización de Escombros', icon: '🏗️' },
  { id: 'llantas', name_es: 'Pirólisis de Llantas Usadas', icon: '🚗' },
  { id: 'residuos-hospitalarios', name_es: 'Tratamiento Eco de Residuos Hospitalarios', icon: '🏥' },
  { id: 'aceite-usado', name_es: 'Conversión de Aceite en Biodiésel', icon: '🛢️' },
  { id: 'basura-espacial', name_es: 'Monitoreo de Basura Espacial', icon: '🛰️' },
  { id: 'desechos-agricolas', name_es: 'Pellets de Desechos Agrícolas', icon: '🌾' },
  { id: 'textiles-reciclaje', name_es: 'Hilado de Textiles Reciclados', icon: '👕' },
  { id: 'vidrio', name_es: 'Trituración y Venta de Vidrio', icon: '🍾' },
  { id: 'metales-chatarra', name_es: 'Clasificación de Chatarra', icon: '⚙️' },
  { id: 'basura-organica-biogas', name_es: 'Digestión Anaerobia de Orgánicos', icon: '🦠' },
  { id: 'carton-papel', name_es: 'Recuperación de Cartón y Papel', icon: '📦' },
  { id: 'colillas', name_es: 'Reciclaje de Colillas de Cigarro', icon: '🚬' },
  { id: 'maderas', name_es: 'Reciclaje de Maderas y Pallets', icon: '🪵' },
  { id: 'recogida-ia', name_es: 'Rutas de Basura Optimizadas por IA', icon: '🗺️' },
  { id: 'residuos-quimicos', name_es: 'Neutralización de Químicos', icon: '🧪' },
  { id: 'upcycling-muebles', name_es: 'Restauración de Muebles Viejos', icon: '🪑' },

  // Reciclaje de Plásticos (20)
  { id: 'pet-botellas', name_es: 'Reciclaje de Botellas PET', icon: '🥤' },
  { id: 'plastico-oceanos', name_es: 'Extracción de Plástico Marino', icon: '🐢' },
  { id: 'bioplasticos', name_es: 'Fabricación de Bioplásticos', icon: '🌱' },
  { id: 'impresion-3d-plastico', name_es: 'Filamento 3D de PET Reciclado', icon: '🖨️' },
  { id: 'plastico-construccion', name_es: 'Ladrillos de Plástico Reciclado', icon: '🧱' },
  { id: 'microplasticos', name_es: 'Filtros de Microplásticos', icon: '🔬' },
  { id: 'reciclaje-quimico', name_es: 'Reciclaje Químico de Plásticos', icon: '⚗️' },
  { id: 'redes-pesca', name_es: 'Reciclaje de Redes de Pesca', icon: '🎣' },
  { id: 'empaques-comestibles', name_es: 'Empaques Biodegradables Comestibles', icon: '🍎' },
  { id: 'plastico-textil', name_es: 'Ropa Hecha con PET Reciclado', icon: '👗' },
  { id: 'tapas-plastico', name_es: 'Mobiliario con Tapas de Plástico', icon: '🛋️' },
  { id: 'madera-plastica', name_es: 'Madera Plástica para Exteriores', icon: '🪵' },
  { id: 'plastico-agricola', name_es: 'Reciclaje de Plástico de Invernadero', icon: '⛺' },
  { id: 'juguetes-eco', name_es: 'Juguetes de Plástico Reciclado', icon: '🧸' },
  { id: 'empaques-hongos', name_es: 'Empaques a base de Micelio', icon: '🍄' },
  { id: 'bolsas-yuca', name_es: 'Bolsas Solubles de Yuca', icon: '🛍️' },
  { id: 'botellas-compostables', name_es: 'Botellas de Algas Marinas', icon: '🌊' },
  { id: 'plastico-asfalto', name_es: 'Asfalto Modificado con Plástico', icon: '🛣️' },
  { id: 'banco-plastico', name_es: 'Bancos de Plástico Solidarios', icon: '💳' },
  { id: 'separacion-optica', name_es: 'Robots de Separación Óptica de PET', icon: '🤖' },

  // Agricultura y Alimentos (20)
  { id: 'hidroponia', name_es: 'Sistemas Hidropónicos', icon: '💧' },
  { id: 'acuaponia', name_es: 'Acuaponía Integrada', icon: '🐟' },
  { id: 'agricultura-vertical', name_es: 'Agricultura Vertical Urbana', icon: '🏢' },
  { id: 'permacultura', name_es: 'Diseño de Permacultura', icon: '🌿' },
  { id: 'regenerativa', name_es: 'Agricultura Regenerativa', icon: '🚜' },
  { id: 'agroforesteria', name_es: 'Sistemas Agroforestales', icon: '🌳' },
  { id: 'control-plagas-bio', name_es: 'Control Biológico de Plagas', icon: '🐞' },
  { id: 'fertilizantes-organicos', name_es: 'Producción de Biofertilizantes', icon: '💩' },
  { id: 'semillas-locales', name_es: 'Bancos de Semillas Autóctonas', icon: '🌱' },
  { id: 'carne-vegetal', name_es: 'Alternativas de Carne Plant-Based', icon: '🍔' },
  { id: 'insectos-comestibles', name_es: 'Harina de Insectos Comestibles', icon: '🦗' },
  { id: 'hongos-gourmet', name_es: 'Cultivo de Hongos en Residuos', icon: '🍄' },
  { id: 'rescate-alimentos', name_es: 'App de Rescate de Comida Fea', icon: '📱' },
  { id: 'huertos-urbanos', name_es: 'Gestión de Huertos Comunitarios', icon: '🏡' },
  { id: 'polinizadores', name_es: 'Santuarios de Abejas', icon: '🐝' },
  { id: 'riego-inteligente', name_es: 'Riego con Sensores IoT', icon: '🚿' },
  { id: 'algas-agricolas', name_es: 'Algas como Fertilizante', icon: '🌿' },
  { id: 'deshidratacion-solar', name_es: 'Deshidratación Solar de Alimentos', icon: '☀️' },
  { id: 'leches-vegetales', name_es: 'Lácteos a base de Plantas', icon: '🥛' },
  { id: 'empaques-retornables', name_es: 'Sistema de Envases Retornables', icon: '♻️' },

  // Movilidad Sostenible (20)
  { id: 'bicicletas-electricas', name_es: 'Alquiler de E-Bikes', icon: '🚲' },
  { id: 'scooters', name_es: 'Micromovilidad Compartida', icon: '🛴' },
  { id: 'carpooling', name_es: 'App de Viajes Compartidos', icon: '🚗' },
  { id: 'buses-electricos', name_es: 'Flotas de Buses Eléctricos', icon: '🚌' },
  { id: 'logistica-ultima-milla', name_es: 'Entregas en Bicicletas de Carga', icon: '📦' },
  { id: 'rutas-peatonales', name_es: 'Diseño de Rutas Peatonales', icon: '🚶' },
  { id: 'conversiones-ev', name_es: 'Conversión de Autos a Eléctricos', icon: '⚡' },
  { id: 'hidrogeno-vehiculos', name_es: 'Vehículos de Hidrógeno', icon: '💧' },
  { id: 'pavimento-eco', name_es: 'Ciclovías de Plástico Reciclado', icon: '🛣️' },
  { id: 'estacionamiento-bici', name_es: 'Parqueaderos Seguros para Bicis', icon: '🅿️' },
  { id: 'transporte-fluvial', name_es: 'Botes Eléctricos Solares', icon: '🚤' },
  { id: 'optimizacion-flotas', name_es: 'Software de Ahorro de Combustible', icon: '💻' },
  { id: 'trenes-baterias', name_es: 'Trenes Alimentados por Baterías', icon: '🚄' },
  { id: 'aviacion-sostenible', name_es: 'Combustibles de Aviación SAF', icon: '✈️' },
  { id: 'movilidad-rural', name_es: 'Transporte Eléctrico Rural', icon: '🌾' },
  { id: 'vuelos-compartidos', name_es: 'Vuelos Chárter Optimizados', icon: '🛩️' },
  { id: 'app-transporte-publico', name_es: 'App de Transporte Público Integrado', icon: '📱' },
  { id: 'mantenimiento-ev', name_es: 'Talleres Especializados en EV', icon: '🔧' },
  { id: 'baterias-servicio', name_es: 'Suscripción de Baterías para Motos', icon: '🔋' },
  { id: 'drones-carga', name_es: 'Reparto Médico con Drones', icon: '🚁' },

  // Conservación del Agua (20)
  { id: 'captacion-lluvia', name_es: 'Sistemas de Captación de Lluvia', icon: '🌧️' },
  { id: 'desalinizacion-solar', name_es: 'Desalinización por Energía Solar', icon: '☀️' },
  { id: 'purificacion-filtros', name_es: 'Filtros de Agua Bio-basados', icon: '🚰' },
  { id: 'aguas-grises', name_es: 'Reutilización de Aguas Grises', icon: '🚿' },
  { id: 'monitoreo-fugas', name_es: 'Sensores de Fugas en Redes', icon: '📡' },
  { id: 'inodoros-secos', name_es: 'Inodoros de Compostaje', icon: '🚽' },
  { id: 'tratamiento-humedales', name_es: 'Humedales Artificiales', icon: '🦆' },
  { id: 'riego-goteo', name_es: 'Kits de Riego por Goteo', icon: '💧' },
  { id: 'condensacion-aire', name_es: 'Generadores de Agua Atmosférica', icon: '☁️' },
  { id: 'restauracion-cuencas', name_es: 'Restauración de Cuencas', icon: '🏞️' },
  { id: 'limpieza-rios', name_es: 'Barreras Atrapa-Plástico Flotantes', icon: '🌊' },
  { id: 'biofiltros', name_es: 'Biofiltros de Arena', icon: '🏜️' },
  { id: 'software-agua', name_es: 'Gestión Hídrica Agrícola', icon: '💻' },
  { id: 'hidrogeles', name_es: 'Hidrogeles Retenedores para Cultivos', icon: '🌱' },
  { id: 'tratamiento-uv', name_es: 'Desinfección de Agua por UV', icon: '☀️' },
  { id: 'piscinas-naturales', name_es: 'Piscinas sin Cloro (Ecológicas)', icon: '🏊' },
  { id: 'duchas-ahorro', name_es: 'Duchas con Recirculación Inmediata', icon: '🚿' },
  { id: 'proteccion-acuiferos', name_es: 'Monitorización de Aguas Subterráneas', icon: '🕳️' },
  { id: 'lavaderos-eco', name_es: 'Lavaderos de Autos sin Agua', icon: '🚗' },
  { id: 'bebidas-responsables', name_es: 'Bebidas de Fuentes Regenerativas', icon: '🥤' },

  // Arquitectura y Bioconstrucción (20)
  { id: 'casas-tierra', name_es: 'Construcción en Tapial o Adobe', icon: '🧱' },
  { id: 'bambu', name_es: 'Estructuras de Bambú', icon: '🎋' },
  { id: 'techos-verdes', name_es: 'Diseño de Techos Vivos', icon: '🌿' },
  { id: 'aislamiento-natural', name_es: 'Aislamiento Térmico de Cáñamo', icon: '🧥' },
  { id: 'pinturas-ecologicas', name_es: 'Pinturas sin VOCs', icon: '🎨' },
  { id: 'casas-pasivas', name_es: 'Diseño de Estándar Passivhaus', icon: '🏠' },
  { id: 'iluminacion-natural', name_es: 'Tubos de Luz Solar', icon: '☀️' },
  { id: 'tiny-houses', name_es: 'Micro-casas Sustentables', icon: '🏡' },
  { id: 'muros-verdes', name_es: 'Jardines Verticales Interiores', icon: '🌱' },
  { id: 'domotica-eco', name_es: 'Casas Inteligentes Eficientes', icon: '🔌' },
  { id: 'cemento-carbono', name_es: 'Hormigón que Absorbe CO2', icon: '🏭' },
  { id: 'madera-certificada', name_es: 'Construcción en Madera CLT', icon: '🌲' },
  { id: 'ventanas-inteligentes', name_es: 'Vidrios Fotovoltaicos', icon: '🪟' },
  { id: 'ventilacion-cruzada', name_es: 'Sistemas de Enfriamiento Pasivo', icon: '🌬️' },
  { id: 'refugios-eco', name_es: 'Refugios de Emergencia Modulares', icon: '⛺' },
  { id: 'baldosas-recicladas', name_es: 'Pisos de Caucho Reciclado', icon: '⬛' },
  { id: 'diseno-bioclimatico', name_es: 'Consultoría Bioclimática', icon: '📐' },
  { id: 'bano-seco', name_es: 'Baños Secos para Zonas Rurales', icon: '🚽' },
  { id: 'acustica-eco', name_es: 'Paneles Acústicos de Hongos', icon: '🍄' },
  { id: 'urbanismo-verde', name_es: 'Planificación de Eco-Barrios', icon: '🏙️' },

  // Conservación y Ecosistemas (20)
  { id: 'reforestacion-drones', name_es: 'Reforestación con Drones', icon: '🚁' },
  { id: 'monitoreo-fauna', name_es: 'Cámaras Trampa Inteligentes', icon: '📷' },
  { id: 'corales', name_es: 'Restauración de Arrecifes de Coral', icon: '🪸' },
  { id: 'manglares', name_es: 'Protección de Manglares', icon: '🌳' },
  { id: 'bonos-carbono', name_es: 'Certificación de Bonos de Carbono', icon: '💰' },
  { id: 'turismo-conservacion', name_es: 'Ecoturismo Científico', icon: '🏕️' },
  { id: 'rescate-animal', name_es: 'Santuarios de Fauna Silvestre', icon: '🦁' },
  { id: 'control-invasoras', name_es: 'Manejo de Especies Invasoras', icon: '🦎' },
  { id: 'proteccion-humedales', name_es: 'Conservación de Turberas', icon: '🦆' },
  { id: 'bancos-genetico', name_es: 'Bancos de ADN Silvestre', icon: '🧬' },
  { id: 'patrullaje-drones', name_es: 'Prevención de Tala Ilegal con Drones', icon: '🚨' },
  { id: 'corredores-biologicos', name_es: 'Diseño de Corredores Biológicos', icon: '🐆' },
  { id: 'limpieza-playas', name_es: 'Red de Limpieza de Océanos', icon: '🏖️' },
  { id: 'apicultura-silvestre', name_es: 'Conservación de Abejas Nativas', icon: '🐝' },
  { id: 'educacion-ambiental', name_es: 'Aulas de Naturaleza', icon: '🦉' },
  { id: 'caza-furtiva', name_es: 'Sensores Acústicos Anti-caza', icon: '🎙️' },
  { id: 'bio-bardas', name_es: 'Bio-bardas para Ríos', icon: '🌊' },
  { id: 'restauracion-minera', name_es: 'Remediación de Suelos Mineros', icon: '⛏️' },
  { id: 'certificacion-biodiversidad', name_es: 'Sellos de Biodiversidad', icon: '✅' },
  { id: 'fondos-verdes', name_es: 'Crowdfunding para Conservación', icon: '📈' },

  // Educación, Software y Misceláneos (40)
  { id: 'app-huella', name_es: 'App Calculadora de Huella de Carbono', icon: '📱' },
  { id: 'juegos-eco', name_es: 'Videojuegos de Educación Ambiental', icon: '🎮' },
  { id: 'realidad-virtual', name_es: 'VR del Cambio Climático', icon: '👓' },
  { id: 'marketing-verde', name_es: 'Agencia de Green Marketing', icon: '📢' },
  { id: 'moda-sostenible', name_es: 'Marketplace de Ropa de Segunda Mano', icon: '👗' },
  { id: 'reparacion-ropa', name_es: 'Talleres de Reparación Upcycling', icon: '🧵' },
  { id: 'cosmetica-natural', name_es: 'Cosmética Zero Waste', icon: '💄' },
  { id: 'limpieza-eco', name_es: 'Detergentes a Granel Bio', icon: '🧼' },
  { id: 'asesoria-esg', name_es: 'Consultoría ESG para Empresas', icon: '👔' },
  { id: 'finanzas-verdes', name_es: 'Banca Ética y Sostenible', icon: '🏦' },
  { id: 'seguros-climaticos', name_es: 'Seguros contra Riesgo Climático', icon: '🛡️' },
  { id: 'etiquetas-inteligentes', name_es: 'Trazabilidad Blockchain de Alimentos', icon: '🔗' },
  { id: 'certificacion-b', name_es: 'Consultoría para Certificación B Corp', icon: '🅱️' },
  { id: 'podcast-ambiental', name_es: 'Red de Podcasts de Sostenibilidad', icon: '🎙️' },
  { id: 'ferias-eco', name_es: 'Organización de Ferias Sostenibles', icon: '🎪' },
  { id: 'cattering-vegano', name_es: 'Catering Plant-Based para Eventos', icon: '🥗' },
  { id: 'eventos-zero-waste', name_es: 'Gestión Zero Waste de Festivales', icon: '🎊' },
  { id: 'regalos-corporativos', name_es: 'Regalos Empresariales Ecológicos', icon: '🎁' },
  { id: 'juguetes-madera', name_es: 'Juguetería Sustentable', icon: '🚂' },
  { id: 'libros-eco', name_es: 'Editorial de Cuentos Ambientales', icon: '📚' },
  { id: 'libreria-segunda', name_es: 'Intercambio de Libros Usados', icon: '📖' },
  { id: 'alquiler-herramientas', name_es: 'Biblioteca de Herramientas', icon: '🔨' },
  { id: 'alquiler-ropa', name_es: 'Renting de Ropa de Lujo', icon: '👗' },
  { id: 'reparacion-electronica', name_es: 'Clínica de Dispositivos Móviles', icon: '📱' },
  { id: 'certificacion-madera', name_es: 'Auditoría FSC', icon: '🌲' },
  { id: 'turismo-rural', name_es: 'Red de Alojamientos Agroturísticos', icon: '🏡' },
  { id: 'camping-eco', name_es: 'Glamping Autosustentable', icon: '⛺' },
  { id: 'vuelos-carbono', name_es: 'Compensación de Vuelos Corporativos', icon: '✈️' },
  { id: 'abogados-ambientales', name_es: 'Despacho de Derecho Ambiental', icon: '⚖️' },
  { id: 'noticias-eco', name_es: 'Portal de Periodismo Ambiental', icon: '📰' },
  { id: 'inversores-verdes', name_es: 'Red de Ángeles Inversores Cleantech', icon: '💸' },
  { id: 'aceleradora-eco', name_es: 'Incubadora de Startups Verdes', icon: '🚀' },
  { id: 'software-lca', name_es: 'Software Análisis Ciclo de Vida', icon: '📊' },
  { id: 'monitoreo-satelital', name_es: 'Satélites de Detección de Metano', icon: '🛰️' },
  { id: 'climatizacion-inteligente', name_es: 'IA para HVAC Corporativo', icon: '❄️' },
  { id: 'auditoria-energetica', name_es: 'Inspección Térmica de Edificios', icon: '🌡️' },
  { id: 'empaques-retornables-ecom', name_es: 'Sobres Retornables para E-commerce', icon: '✉️' },
  { id: 'pañales-ecologicos', name_es: 'Suscripción de Pañales Lavables', icon: '👶' },
  { id: 'copas-menstruales', name_es: 'Productos de Higiene Reutilizables', icon: '🩸' },
  { id: 'cremacion-eco', name_es: 'Urnas Biodegradables y Compostaje Humano', icon: '⚱️' }
];
