-- Script de inserción de 120 Micro-Apps para Vertical Medio Ambiente

DELETE FROM app_executions;
DELETE FROM plan_apps;
DELETE FROM user_app_overrides;
DELETE FROM micro_apps;

INSERT INTO micro_apps (slug, name_es, name_en, description_es, description_en, icon, form_schema, autofill_presets, prompt_template)
VALUES
('ucam-asset', 'I. Contabilidad Ambiental: UCAM Asset Generator', 'I. Contabilidad Ambiental: UCAM Asset Generator', 'Crea un 'título valor' digital de tu impacto positivo para que puedas venderlo o mostrarlo como un activo de tu empresa.', 'Creates a digital 'security' of your positive impact to sell or show as an asset.', 'Award', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for UCAM Asset Generator'),
('pasivos-invisibles', 'I. Contabilidad Ambiental: Balance de Pasivos Invisibles', 'I. Contabilidad Ambiental: Invisible Liabilities Balance', 'Encuentra las deudas ambientales que no aparecen en tu contabilidad normal, como basura acumulada o contaminación pasada.', 'Finds environmental debts not in normal accounting, like accumulated waste.', 'TrendingDown', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Invisible Liabilities Balance'),
('huella-a-ucam', 'I. Contabilidad Ambiental: Conversor de Huella a UCAM', 'I. Contabilidad Ambiental: Footprint to UCAM Converter', 'Traduce tus toneladas de CO2 o kilos de plástico a 'monedas' de impacto UCAM para facilitar intercambios.', 'Translates CO2 tons to UCAM impact coins for easy exchange.', 'RefreshCw', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Footprint to UCAM Converter'),
('costo-inaccion', 'I. Contabilidad Ambiental: Costo de Inacción', 'I. Contabilidad Ambiental: Cost of Inaction', 'Te muestra cuánto dinero perderá tu negocio si no empiezas a ser sostenible hoy mismo antes de que lleguen las multas.', 'Shows money lost if you don't become sustainable before fines arrive.', 'AlertTriangle', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Cost of Inaction'),
('auditor-activos', 'I. Contabilidad Ambiental: Auditor de Activos Verificables', 'I. Contabilidad Ambiental: Verifiable Assets Auditor', 'Revisa que tus datos sean tan sólidos que cualquier auditor internacional pueda darles el visto bueno.', 'Checks data solidity for international auditors' approval.', 'CheckShield', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Verifiable Assets Auditor'),
('simulador-externalidades', 'I. Contabilidad Ambiental: Simulador de Externalidades', 'I. Contabilidad Ambiental: Externalities Simulator', 'Calcula cuánto le cuesta al planeta tu operación y cómo eso afecta tu rentabilidad real.', 'Calculates planet cost of your operation and real profitability impact.', 'Globe', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Externalities Simulator'),
('brecha-regulatoria', 'I. Contabilidad Ambiental: Monitor de Brecha Regulatoria', 'I. Contabilidad Ambiental: Regulatory Gap Monitor', 'Te avisa qué tan lejos estás de cumplir las nuevas leyes ambientales de Europa y Latinoamérica.', 'Alerts how far you are from meeting new EU/LatAm environmental laws.', 'FileText', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Regulatory Gap Monitor'),
('valuador-capital-natural', 'I. Contabilidad Ambiental: Valuador de Capital Natural', 'I. Contabilidad Ambiental: Natural Capital Valuator', 'Le pone un precio justo al aire limpio, el agua y la sombra que producen los árboles de tu propiedad.', 'Prices clean air, water, and shade produced by your trees.', 'TreePine', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Natural Capital Valuator'),
('registro-trazabilidad', 'I. Contabilidad Ambiental: Registro de Trazabilidad', 'I. Contabilidad Ambiental: Traceability Ledger', 'Un libro contable digital donde nadie puede borrar ni alterar la historia de tus mejoras ambientales.', 'Digital ledger where no one can alter your environmental improvements.', 'Lock', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Traceability Ledger'),
('roi-estrategico', 'I. Contabilidad Ambiental: ROI Estratégico', 'I. Contabilidad Ambiental: Strategic ROI', 'Calcula exactamente en cuánto tiempo recuperarás el dinero que inviertas en tecnología verde.', 'Calculates exact payback time for green tech investments.', 'Sun', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Strategic ROI'),
('gestor-creditos', 'I. Contabilidad Ambiental: Gestor de Créditos de Impacto', 'I. Contabilidad Ambiental: Impact Credits Manager', 'Una billetera digital para administrar los certificados de ahorro de energía o reciclaje que generas.', 'Digital wallet to manage generated energy/recycling certificates.', 'Wallet', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Impact Credits Manager'),
('tax-carbon-predict', 'I. Contabilidad Ambiental: Tax-Carbon Predictor', 'I. Contabilidad Ambiental: Tax-Carbon Predictor', 'Predice cuánto tendrás que pagar en impuestos por contaminar en los próximos 5 años.', 'Predicts pollution tax payments for the next 5 years.', 'BarChart', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Tax-Carbon Predictor'),
('flujo-fondos-verdes', 'I. Contabilidad Ambiental: Flujo de Fondos Verdes', 'I. Contabilidad Ambiental: Green Cash Flow', 'Proyecta cuánto dinero extra entrará a tu caja por vender bonos de carbono o certificados UCAM.', 'Projects extra cash from selling carbon bonds or UCAM certificates.', 'TrendingUp', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Green Cash Flow'),
('sna-lms-integrator', 'I. Contabilidad Ambiental: SNA-LMS Integrator', 'I. Contabilidad Ambiental: SNA-LMS Integrator', 'Conecta lo que tus empleados aprenden con los resultados reales de ahorro ambiental de la empresa.', 'Connects employee learning with real environmental savings.', 'BookOpen', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for SNA-LMS Integrator'),
('bio-equity-ledger', 'I. Contabilidad Ambiental: Bio-Equity Ledger', 'I. Contabilidad Ambiental: Bio-Equity Ledger', 'Registra la variedad de plantas y animales de tu zona como un patrimonio que aumenta el valor de tu tierra.', 'Logs local biodiversity as an asset increasing land value.', 'Map', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Bio-Equity Ledger'),
('costos-ocultos-residuos', 'I. Contabilidad Ambiental: Costos Ocultos de Residuos', 'I. Contabilidad Ambiental: Hidden Waste Costs', 'Te dice cuánto dinero estás botando a la basura en forma de materia prima que aún sirve.', 'Shows money thrown away as still useful raw materials.', 'Trash2', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Hidden Waste Costs'),
('green-interest', 'I. Contabilidad Ambiental: Green-Interest Optimizer', 'I. Contabilidad Ambiental: Green-Interest Optimizer', 'Te ayuda a negociar con el banco para que te bajen los intereses si demuestras que eres una empresa limpia.', 'Helps negotiate lower bank interest rates by proving you're clean.', 'Percent', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Green-Interest Optimizer'),
('sdg-budgeting', 'I. Contabilidad Ambiental: SDG-Budgeting Tool', 'I. Contabilidad Ambiental: SDG-Budgeting Tool', 'Organiza tus gastos para que cada peso que inviertas ayude a cumplir los Objetivos de Desarrollo Sostenible.', 'Organizes spending so every dollar helps meet UN SDGs.', 'Target', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for SDG-Budgeting Tool'),
('risk-climate', 'I. Contabilidad Ambiental: Risk-Climate Scorecard', 'I. Contabilidad Ambiental: Risk-Climate Scorecard', 'Te da una calificación de seguridad para saber si tus bodegas o plantas están en riesgo por el clima.', 'Gives a safety score for warehouse/plant climate risk.', 'ShieldAlert', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Risk-Climate Scorecard'),
('esg-autoreport', 'I. Contabilidad Ambiental: ESG-AutoReport', 'I. Contabilidad Ambiental: ESG-AutoReport', 'Escribe por ti el reporte de sostenibilidad que te piden los bancos o socios internacionales.', 'Writes the sustainability report required by banks/partners.', 'FileCheck', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for ESG-AutoReport'),
('disruptor-finder', 'II. Medicina Ambiental: Disruptor-Endocrino Finder', 'II. Medicina Ambiental: Endocrine Disruptor Finder', 'Analiza si tus productos de aseo o belleza tienen químicos que alteran tus hormonas.', 'Analyzes if cleaning/beauty products have hormone-altering chemicals.', 'Search', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Endocrine Disruptor Finder'),
('bau-screener', 'II. Medicina Ambiental: Bau-Biologie Screener', 'II. Medicina Ambiental: Building Biology Screener', 'Un examen para tu oficina o casa que detecta si el edificio te está enfermando.', 'Test for home/office to detect if the building is making you sick.', 'Home', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Building Biology Screener'),
('neuro-toxic-map', 'II. Medicina Ambiental: Neuro-Toxic Risk Map', 'II. Medicina Ambiental: Neuro-Toxic Risk Map', 'Te dice si vives o trabajas cerca de zonas con químicos que afectan el cerebro y los nervios.', 'Shows if you live/work near brain/nerve-affecting chemical zones.', 'MapPin', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Neuro-Toxic Risk Map'),
('pfas-check', 'II. Medicina Ambiental: PFAS-Check', 'II. Medicina Ambiental: PFAS-Check', 'Identifica 'químicos eternos' en tu agua o sartenes que no se borran del cuerpo y pueden ser peligrosos.', 'Identifies 'forever chemicals' in water/pans that stay in the body.', 'Droplet', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for PFAS-Check'),
('microplastic-calc', 'II. Medicina Ambiental: Microplastic Exposure Calc', 'II. Medicina Ambiental: Microplastic Exposure Calc', 'Estima cuántas partículas diminutas de plástico estás respirando o comiendo sin darte cuenta.', 'Estimates microplastic particles breathed or eaten unknowingly.', 'Wind', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Microplastic Exposure Calc'),
('emf-safety', 'II. Medicina Ambiental: EMF-Safety Distance', 'II. Medicina Ambiental: EMF-Safety Distance', 'Calcula a qué distancia debes estar de routers, cables y antenas para que no afecten tu salud.', 'Calculates safe distance from routers/antennas for your health.', 'Radio', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for EMF-Safety Distance'),
('voc-health', 'II. Medicina Ambiental: VOC-Health Impact', 'II. Medicina Ambiental: VOC-Health Impact', 'Mide si el olor a pintura o pegamento en tu trabajo está dañando tus pulmones.', 'Measures if paint/glue smells at work are damaging lungs.', 'Activity', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for VOC-Health Impact'),
('heavy-metal-bio', 'II. Medicina Ambiental: Heavy-Metal Bio-Accumulation', 'II. Medicina Ambiental: Heavy-Metal Bio-Accumulation', 'Te explica cómo metales como el plomo se guardan en tu cuerpo y qué riesgo tienes según tu zona.', 'Explains how heavy metals store in the body and location risks.', 'AlertCircle', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Heavy-Metal Bio-Accumulation'),
('circadian-light-opt', 'II. Medicina Ambiental: Circadian-Light Optimizer', 'II. Medicina Ambiental: Circadian-Light Optimizer', 'Te dice cómo configurar tus luces para que tu cuerpo sepa cuándo dormir y cuándo estar alerta.', 'How to configure lights so your body knows when to sleep/be alert.', 'Sun', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Circadian-Light Optimizer'),
('toxic-load', 'II. Medicina Ambiental: Toxic-Load Calculator', 'II. Medicina Ambiental: Toxic-Load Calculator', 'Calcula cuántos químicos has acumulado en tu vida basándose en dónde has vivido y trabajado.', 'Calculates accumulated chemicals based on living/working history.', 'Battery', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Toxic-Load Calculator'),
('allergy-pollution', 'II. Medicina Ambiental: Allergy-Pollution Alert', 'II. Medicina Ambiental: Allergy-Pollution Alert', 'Te avisa cuando el smog y el polen se juntan para evitar ataques de asma o rinitis.', 'Alerts when smog and pollen mix to avoid asthma attacks.', 'Cloud', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Allergy-Pollution Alert'),
('skin-barrier', 'II. Medicina Ambiental: Skin-Barrier Protector', 'II. Medicina Ambiental: Skin-Barrier Protector', 'Analiza si tus jabones industriales están rompiendo la protección natural de tu piel.', 'Analyzes if industrial soaps break your skin's natural barrier.', 'Shield', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Skin-Barrier Protector'),
('radon-estimator', 'II. Medicina Ambiental: Radon-Risk Estimator', 'II. Medicina Ambiental: Radon-Risk Estimator', 'Detecta si en el suelo de tu edificio hay gas radón, un riesgo invisible pero importante.', 'Detects radon gas in building soil, an invisible risk.', 'Thermometer', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Radon-Risk Estimator'),
('detox-support', 'II. Medicina Ambiental: Detox-Support Nutrition', 'II. Medicina Ambiental: Detox-Support Nutrition', 'Guía médica de alimentos que ayudan a tu hígado y riñones a sacar los metales pesados del cuerpo.', 'Medical food guide to help liver/kidneys extract heavy metals.', 'Heart', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Detox-Support Nutrition'),
('noise-stress-mon', 'II. Medicina Ambiental: Noise-Stress Monitor', 'II. Medicina Ambiental: Noise-Stress Monitor', 'Te muestra cómo el ruido de las máquinas o el tráfico está subiendo tus niveles de estrés y presión.', 'Shows how machine/traffic noise raises stress and blood pressure.', 'Volume2', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Noise-Stress Monitor'),
('water-contaminant', 'II. Medicina Ambiental: Water-Contaminant Decoder', 'II. Medicina Ambiental: Water-Contaminant Decoder', 'Traduce esos informes difíciles de los laboratorios de agua a palabras que tú entiendas.', 'Translates complex water lab reports into understandable words.', 'Droplets', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Water-Contaminant Decoder'),
('eco-psychology', 'II. Medicina Ambiental: Eco-Psychology Support', 'II. Medicina Ambiental: Eco-Psychology Support', 'Herramientas para manejar la tristeza o el miedo que causa ver el daño al planeta (eco-ansiedad).', 'Tools to manage sadness/fear from planetary damage (eco-anxiety).', 'Smile', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Eco-Psychology Support'),
('thermal-strain', 'II. Medicina Ambiental: Thermal-Strain Index', 'II. Medicina Ambiental: Thermal-Strain Index', 'Te avisa cuando el calor y la humedad en el trabajo ya son peligrosos para el corazón.', 'Alerts when work heat/humidity becomes dangerous for the heart.', 'ThermometerSun', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Thermal-Strain Index'),
('food-additive-tox', 'II. Medicina Ambiental: Food-Additive Toxicity', 'II. Medicina Ambiental: Food-Additive Toxicity', 'Te dice qué colorantes y conservantes de tu comida son seguros y cuáles es mejor evitar.', 'Shows which food dyes/preservatives are safe and which to avoid.', 'Coffee', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Food-Additive Toxicity'),
('health-roi', 'II. Medicina Ambiental: Health-ROI Simulator', 'II. Medicina Ambiental: Health-ROI Simulator', 'Calcula cuánto dinero ahorra una empresa al tener empleados sanos gracias a un aire más puro.', 'Calculates money saved by having healthy employees via pure air.', 'PieChart', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Health-ROI Simulator'),
('pyro-yield-pred', 'III. Ingeniería Pirólisis: Pyro-Yield Predictor', 'III. Ingeniería Pirólisis: Pyro-Yield Predictor', 'Te dice cuánto carbón y aceite sacarás de una tonelada de madera o plástico viejo.', 'Predicts coal/oil yield from a ton of wood or old plastic.', 'Flame', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Pyro-Yield Predictor'),
('syngas-btu', 'III. Ingeniería Pirólisis: Syngas-BTU Calculator', 'III. Ingeniería Pirólisis: Syngas-BTU Calculator', 'Mide cuánta energía tiene el gas que sale de tu horno para ver si puedes generar electricidad.', 'Measures gas energy from kiln to see if electricity can be generated.', 'Zap', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Syngas-BTU Calculator'),
('polymer-pyro', 'III. Ingeniería Pirólisis: Polymer-Pyrolysis ID', 'III. Ingeniería Pirólisis: Polymer-Pyrolysis ID', 'Te ayuda a identificar qué plásticos sirven para quemar y cuáles para hacer aceite.', 'Identifies which plastics to burn and which for oil.', 'Box', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Polymer-Pyrolysis ID'),
('mass-energy-bal', 'III. Ingeniería Pirólisis: Mass-Energy Balance Pro', 'III. Ingeniería Pirólisis: Mass-Energy Balance Pro', 'Asegura que tu máquina no gaste más energía de la que produce.', 'Ensures your machine doesn't spend more energy than it produces.', 'Scale', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Mass-Energy Balance Pro'),
('reactor-sizing', 'III. Ingeniería Pirólisis: Reactor-Sizing Tool', 'III. Ingeniería Pirólisis: Reactor-Sizing Tool', 'Te da las medidas exactas que debe tener tu horno según cuánta basura quieras procesar.', 'Exact kiln dimensions based on waste processing volume.', 'Maximize', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Reactor-Sizing Tool'),
('biochar-quality-an', 'III. Ingeniería Pirólisis: Biochar-Quality Analyzer', 'III. Ingeniería Pirólisis: Biochar-Quality Analyzer', 'Revisa si tu carbón vegetal sirve para venderlo como abono o como filtro de agua.', 'Checks if biochar is sellable as fertilizer or water filter.', 'CheckSquare', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Biochar-Quality Analyzer'),
('emission-scrubber', 'III. Ingeniería Pirólisis: Emission-Scrubber Calc', 'III. Ingeniería Pirólisis: Emission-Scrubber Calc', 'Calcula cuánta agua necesitas para lavar el humo de tu chimenea y que salga limpio.', 'Calculates water needed to wash chimney smoke clean.', 'CloudRain', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Emission-Scrubber Calc'),
('thermal-loss-det', 'III. Ingeniería Pirólisis: Thermal-Loss Detector', 'III. Ingeniería Pirólisis: Thermal-Loss Detector', 'Te señala por dónde se está escapando el calor de tu máquina para que no gastes leña o gas de más.', 'Points out machine heat leaks to save wood/gas.', 'ThermometerSnowflake', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Thermal-Loss Detector'),
('moisture-impact', 'III. Ingeniería Pirólisis: Moisture-Impact Simulator', 'III. Ingeniería Pirólisis: Moisture-Impact Simulator', 'Te dice qué tanto afecta la humedad de tu leña al tiempo que tarda en quemarse.', 'Shows how wood moisture affects burning time.', 'Droplet', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Moisture-Impact Simulator'),
('tire-carbon-black', 'III. Ingeniería Pirólisis: Tire-Carbon-Black Recovery', 'III. Ingeniería Pirólisis: Tire-Carbon-Black Recovery', 'Calcula cuánto acero y polvo negro puedes sacar de 100 llantas usadas.', 'Calculates steel and black powder from 100 used tires.', 'Circle', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Tire-Carbon-Black Recovery'),
('sludge-to-energy', 'III. Ingeniería Pirólisis: Sludge-to-Energy Designer', 'III. Ingeniería Pirólisis: Sludge-to-Energy Designer', 'Una guía para convertir el lodo de las alcantarillas en energía útil.', 'Guide to convert sewage sludge into useful energy.', 'Trash2', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Sludge-to-Energy Designer'),
('heat-exchanger', 'III. Ingeniería Pirólisis: Heat-Exchanger Optimizer', 'III. Ingeniería Pirólisis: Heat-Exchanger Optimizer', 'Diseña tubos para que el calor que sale de tu horno sirva para calentar agua gratis.', 'Designs pipes to use kiln heat for free water heating.', 'RefreshCw', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Heat-Exchanger Optimizer'),
('pyrolysis-oil-stab', 'III. Ingeniería Pirólisis: Pyrolysis-Oil Stabilizer', 'III. Ingeniería Pirólisis: Pyrolysis-Oil Stabilizer', 'Consejos para mejorar la calidad del aceite que fabricas para que no se dañe.', 'Tips to improve manufactured oil quality to prevent degradation.', 'Settings', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Pyrolysis-Oil Stabilizer'),
('safety-pressure', 'III. Ingeniería Pirólisis: Safety-Pressure Valve Calc', 'III. Ingeniería Pirólisis: Safety-Pressure Valve Calc', 'Calcula qué tan fuerte debe ser tu válvula para que el horno no explote por presión.', 'Calculates valve strength to prevent pressure explosions.', 'AlertCircle', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Safety-Pressure Valve Calc'),
('feedstock-mix-mast', 'III. Ingeniería Pirólisis: Feedstock-Mix Master', 'III. Ingeniería Pirólisis: Feedstock-Mix Master', 'La receta perfecta: cuánto plástico y cuánta madera mezclar para que el fuego sea estable.', 'Perfect recipe: plastic/wood ratio for a stable fire.', 'List', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Feedstock-Mix Master'),
('catalyst-selection', 'III. Ingeniería Pirólisis: Catalyst-Selection Guide', 'III. Ingeniería Pirólisis: Catalyst-Selection Guide', 'Te recomienda polvos químicos para que tu proceso funcione a menos temperatura y sea más barato.', 'Recommends chemicals to lower process temperature and cost.', 'FlaskConical', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Catalyst-Selection Guide'),
('ash-chemical-prof', 'III. Ingeniería Pirólisis: Ash-Chemical Profile', 'III. Ingeniería Pirólisis: Ash-Chemical Profile', 'Analiza si la ceniza que te sobra sirve para mezclar con cemento y hacer ladrillos.', 'Analyzes if leftover ash is useful for cement brick mixing.', 'Archive', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Ash-Chemical Profile'),
('process-duration', 'III. Ingeniería Pirólisis: Process-Duration Timer', 'III. Ingeniería Pirólisis: Process-Duration Timer', 'Te dice exactamente cuántos minutos debe estar la basura en el horno para que se convierta en carbón.', 'Exact kiln minutes needed to turn waste into coal.', 'Clock', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Process-Duration Timer'),
('maintenance-pred', 'III. Ingeniería Pirólisis: Maintenance-Predictor AI', 'III. Ingeniería Pirólisis: Maintenance-Predictor AI', 'Te avisa cuándo debes limpiar tu máquina antes de que se rompa por el uso.', 'Alerts when to clean machine before it breaks from use.', 'Tool', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Maintenance-Predictor AI'),
('plant-efficiency', 'III. Ingeniería Pirólisis: Plant-Efficiency Logger', 'III. Ingeniería Pirólisis: Plant-Efficiency Logger', 'Un diario digital para anotar cuánto produjiste cada día y ver si tu planta es rentable.', 'Digital diary to log daily production and profitability.', 'FileText', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Plant-Efficiency Logger'),
('reverse-log-plan', 'IV. Economía Circular: Reverse-Logistics Planner', 'IV. Economía Circular: Reverse-Logistics Planner', 'Diseña la ruta más corta para recoger material reciclable y gastar menos gasolina.', 'Designs shortest route for recyclables to save gas.', 'Truck', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Reverse-Logistics Planner'),
('material-flow-sank', 'IV. Economía Circular: Material-Flow Sankey', 'IV. Economía Circular: Material-Flow Sankey', 'Un mapa visual que muestra por dónde entra la materia prima a tu fábrica y por dónde se desperdicia.', 'Visual map of raw material entry and waste points.', 'Share2', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Material-Flow Sankey'),
('upcycling-rank', 'IV. Economía Circular: Upcycling-Potential Ranker', 'IV. Economía Circular: Upcycling-Potential Ranker', 'Te da ideas creativas para convertir tus residuos industriales en productos de lujo.', 'Creative ideas to turn industrial waste into luxury products.', 'Star', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Upcycling-Potential Ranker'),
('ewaste-dismantle', 'IV. Economía Circular: E-Waste Dismantle Guide', 'IV. Economía Circular: E-Waste Dismantle Guide', 'Manual paso a paso para desarmar computadores y sacarles el oro y la plata de forma segura.', 'Step-by-step guide to dismantle PCs for safe gold/silver extraction.', 'Cpu', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for E-Waste Dismantle Guide'),
('recyclability-score', 'IV. Economía Circular: Recyclability Scorecard', 'IV. Economía Circular: Recyclability Scorecard', 'Le da una nota a tu producto para ver qué tan fácil será reciclarlo en el futuro.', 'Grades product to see how easy it is to recycle in the future.', 'Package', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Recyclability Scorecard'),
('cn-ratio', 'IV. Economía Circular: C/N Ratio Composter', 'IV. Economía Circular: C/N Ratio Composter', 'Te dice cuántas hojas secas y cuántas cáscaras de fruta echar a tu abono para que no huela mal.', 'Dry leaves/fruit peel ratio for odor-free compost.', 'Leaf', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for C/N Ratio Composter'),
('zero-waste-audit', 'IV. Economía Circular: Zero-Waste Audit Tool', 'IV. Economía Circular: Zero-Waste Audit Tool', 'Encuentra los puntos exactos de tu empresa donde estás creando basura que podrías evitar.', 'Finds exact company spots creating avoidable trash.', 'CheckCircle', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Zero-Waste Audit Tool'),
('digital-mat-pass', 'IV. Economía Circular: Digital Material Passport', 'IV. Economía Circular: Digital Material Passport', 'Crea una 'cédula' para tu producto que dice de qué está hecho para que siempre se sepa cómo reciclarlo.', 'Product ID showing composition for future recycling.', 'CreditCard', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Digital Material Passport'),
('symbiosis-matcher', 'IV. Economía Circular: Industrial Symbiosis Matcher', 'IV. Economía Circular: Industrial Symbiosis Matcher', 'Un 'Tinder' de basura: busca empresas que necesiten lo que a ti te sobra como materia prima.', 'Waste Tinder: finds companies needing your waste as raw material.', 'Users', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Industrial Symbiosis Matcher'),
('waste-hazard', 'IV. Economía Circular: Waste-Hazard Classifier', 'IV. Economía Circular: Waste-Hazard Classifier', 'Te dice si un químico es peligroso y cómo debes guardarlo para no causar accidentes.', 'Shows if a chemical is hazardous and how to store it safely.', 'AlertTriangle', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Waste-Hazard Classifier'),
('plastic-density', 'IV. Economía Circular: Plastic-Density Tester', 'IV. Economía Circular: Plastic-Density Tester', 'Una prueba sencilla con agua y sal para saber exactamente qué tipo de plástico tienes en la mano.', 'Simple water/salt test to identify plastic type.', 'Droplet', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Plastic-Density Tester'),
('water-circular', 'IV. Economía Circular: Water-Circular Designer', 'IV. Economía Circular: Water-Circular Designer', 'Diseña un sistema para que el agua que usas en una máquina sirva para otra en lugar de botarla.', 'Designs a system to reuse machine water instead of wasting it.', 'RefreshCcw', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Water-Circular Designer'),
('pallet-tracker', 'IV. Economía Circular: Pallet-Life-Cycle Tracker', 'IV. Economía Circular: Pallet-Life-Cycle Tracker', 'Controla cuántas estibas tienes y cuántas veces se han reparado para que duren más años.', 'Tracks pallets and repairs so they last more years.', 'Archive', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Pallet-Life-Cycle Tracker'),
('textile-analyzer', 'IV. Economía Circular: Textile-Fiber Analyzer', 'IV. Economía Circular: Textile-Fiber Analyzer', 'Te ayuda a saber si una tela es algodón natural o poliéster plástico para poder reciclarla.', 'Helps identify if fabric is natural cotton or plastic polyester.', 'Scissors', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Textile-Fiber Analyzer'),
('biodegradability', 'IV. Economía Circular: Biodegradability Timer', 'IV. Economía Circular: Biodegradability Timer', 'Te dice cuánto tardará un material en desaparecer si cae al suelo, al agua o al compost.', 'Shows how long a material takes to disappear in soil/water/compost.', 'Clock', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Biodegradability Timer'),
('paper-to-tree', 'IV. Economía Circular: Paper-to-Tree Converter', 'IV. Economía Circular: Paper-to-Tree Converter', 'Traduce tus kilos de papel reciclado a número de árboles salvados para tus redes sociales.', 'Translates recycled paper kilos to saved trees for social media.', 'TreePine', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Paper-to-Tree Converter'),
('demolition-inv', 'IV. Economía Circular: Demolition-Inventory Pro', 'IV. Economía Circular: Demolition-Inventory Pro', 'Lista qué ventanas, puertas o cables puedes salvar de una casa vieja antes de tumbarla.', 'Lists salvageable windows/doors from an old house before demolition.', 'Home', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Demolition-Inventory Pro'),
('scrap-value', 'IV. Economía Circular: Scrap-Value Live', 'IV. Economía Circular: Scrap-Value Live', 'Te da el precio real del metal, cartón y plástico en el mercado hoy mismo.', 'Gives real-time market price for scrap metal/cardboard/plastic.', 'DollarSign', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Scrap-Value Live'),
('modular-design', 'IV. Economía Circular: Modular-Design Checklist', 'IV. Economía Circular: Modular-Design Checklist', 'Consejos para fabricar cosas que se puedan desarmar y arreglar fácilmente.', 'Tips to manufacture easily dismantled and repairable items.', 'Grid', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Modular-Design Checklist'),
('green-vendor-aud', 'IV. Economía Circular: Green-Vendor Auditor', 'IV. Economía Circular: Green-Vendor Auditor', 'Revisa si tus proveedores son realmente ecológicos o si solo lo dicen por publicidad.', 'Checks if suppliers are truly eco-friendly or just greenwashing.', 'ShoppingCart', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Green-Vendor Auditor'),
('law-library', 'V. Estrategia y Edu: Law-Library', 'V. Estrategia y Edu: Law-Library', 'Las leyes ambientales de tu país resumidas.', 'Your country's environmental laws summarized.', 'Book', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Law-Library'),
('iso-14001-prep', 'V. Estrategia y Edu: ISO-14001-Prep', 'V. Estrategia y Edu: ISO-14001-Prep', 'Lista de tareas para certificarte internacionalmente.', 'Task list for international certification.', 'List', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for ISO-14001-Prep'),
('ecolabel-verify', 'V. Estrategia y Edu: Ecolabel-Verify', 'V. Estrategia y Edu: Ecolabel-Verify', 'Detecta si un sello Eco es falso (Greenwashing).', 'Detects if an Eco label is fake.', 'ShieldAlert', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Ecolabel-Verify'),
('green-glossary', 'V. Estrategia y Edu: Green-Glossary', 'V. Estrategia y Edu: Green-Glossary', 'Significado de palabras técnicas ambientales.', 'Meaning of technical environmental words.', 'BookOpen', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Green-Glossary'),
('audit-cam', 'V. Estrategia y Edu: Audit-Cam', 'V. Estrategia y Edu: Audit-Cam', 'Toma fotos de problemas ambientales y crea un reporte.', 'Take photos of environmental issues and report.', 'Camera', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Audit-Cam'),
('stakeholder-map', 'V. Estrategia y Edu: Stakeholder-Map', 'V. Estrategia y Edu: Stakeholder-Map', 'Lista de vecinos y grupos que afectan tu negocio.', 'List of neighbors and groups affecting business.', 'Map', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Stakeholder-Map'),
('policy-maker', 'V. Estrategia y Edu: Policy-Maker', 'V. Estrategia y Edu: Policy-Maker', 'Escribe la misión ambiental de tu empresa por ti.', 'Writes your company's environmental mission.', 'FileText', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Policy-Maker'),
('climate-action-planner', 'V. Estrategia y Edu: Climate-Action-Planner', 'V. Estrategia y Edu: Climate-Action-Planner', 'Metas mes a mes para dejar de contaminar.', 'Month-by-month goals to stop polluting.', 'Calendar', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Climate-Action-Planner'),
('eco-trivia', 'V. Estrategia y Edu: Eco-Trivia', 'V. Estrategia y Edu: Eco-Trivia', 'Juego para que tus empleados aprendan a reciclar.', 'Game for employees to learn recycling.', 'HelpCircle', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Eco-Trivia'),
('crisis-response', 'V. Estrategia y Edu: Crisis-Response', 'V. Estrategia y Edu: Crisis-Response', 'Qué hacer si se rompe un tarro de ácido.', 'What to do if an acid jar breaks.', 'AlertCircle', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Crisis-Response'),
('reporting-gri', 'V. Estrategia y Edu: Reporting-GRI', 'V. Estrategia y Edu: Reporting-GRI', 'Llena un formulario y genera tu reporte anual.', 'Fill form and generate annual report.', 'BarChart', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Reporting-GRI'),
('permit-tracker', 'V. Estrategia y Edu: Permit-Tracker', 'V. Estrategia y Edu: Permit-Tracker', 'Te avisa antes de que venza tu licencia de agua.', 'Alerts before your water license expires.', 'Clock', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Permit-Tracker'),
('bio-ethics-app', 'V. Estrategia y Edu: Bio-Ethics-App', 'V. Estrategia y Edu: Bio-Ethics-App', 'Ayuda a decidir dilemas morales sobre naturaleza.', 'Helps decide moral dilemmas regarding nature.', 'Scale', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Bio-Ethics-App'),
('citizen-science', 'V. Estrategia y Edu: Citizen-Science', 'V. Estrategia y Edu: Citizen-Science', 'Sube fotos de animales raros para biólogos.', 'Upload photos of rare animals for biologists.', 'Eye', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Citizen-Science'),
('grant-finder', 'V. Estrategia y Edu: Grant-Finder', 'V. Estrategia y Edu: Grant-Finder', 'Dónde hay dinero regalado para proyectos verdes.', 'Where to find free money for green projects.', 'Search', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Grant-Finder'),
('supply-risk', 'V. Estrategia y Edu: Supply-Risk', 'V. Estrategia y Edu: Supply-Risk', 'Te avisa si tu proveedor está deforestando.', 'Alerts if your supplier is deforesting.', 'Activity', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Supply-Risk'),
('workshop-pro', 'V. Estrategia y Edu: Workshop-Pro', 'V. Estrategia y Edu: Workshop-Pro', 'Ideas para reuniones de equipo sobre ecología.', 'Ideas for team meetings about ecology.', 'Users', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Workshop-Pro'),
('lobby-monitor', 'V. Estrategia y Edu: Lobby-Monitor', 'V. Estrategia y Edu: Lobby-Monitor', 'Qué se decidió hoy en las cumbres del clima.', 'What was decided today at climate summits.', 'Radio', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Lobby-Monitor'),
('eco-impact-simulator', 'V. Estrategia y Edu: Eco-Impact-Simulator', 'V. Estrategia y Edu: Eco-Impact-Simulator', 'Mira cómo se vería el mundo si todos reciclaran.', 'See world if everyone recycled.', 'Globe', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Eco-Impact-Simulator'),
('portal-config', 'V. Estrategia y Edu: Portal-Config', 'V. Estrategia y Edu: Portal-Config', 'Ajusta tus apps favoritas y personales.', 'Adjust your favorite and personal apps.', 'Settings', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Portal-Config'),
('linea-base-exp', 'VI. Proyectos: Línea Base Express', 'VI. Proyectos: Express Baseline', 'Permite establecer la situación inicial de un proyecto (estado 'cero') para poder medir cuánto impacto positivo se genera realmente desde el inicio.', 'Establishes initial project state to measure positive impact generated.', 'Map', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Express Baseline'),
('estructurador-proyectos', 'VI. Proyectos: Estructurador de Proyectos de Impacto', 'VI. Proyectos: Impact Project Structurer', 'Guía al usuario en la creación del documento técnico (pitch deck) necesario para presentar proyectos ante fondos de inversión ambiental.', 'Guides creation of pitch deck for environmental investment funds.', 'Layout', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Impact Project Structurer'),
('calc-adicionalidad', 'VI. Proyectos: Calculadora de Adicionalidad', 'VI. Proyectos: Additionality Calculator', 'Determina si un proyecto ambiental realmente aporta un beneficio nuevo o si es algo que sucedería de todos modos por ley.', 'Determines if an environmental project provides a truly new benefit.', 'PlusCircle', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Additionality Calculator'),
('sim-escalabilidad', 'VI. Proyectos: Simulador de Escalabilidad Técnica', 'VI. Proyectos: Tech Scalability Simulator', 'Evalúa si una solución ambiental pequeña puede crecer 10 o 100 veces manteniendo su eficiencia.', 'Evaluates if a small eco solution can scale 10-100x efficiently.', 'Maximize', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Tech Scalability Simulator'),
('validador-mrv', 'VI. Proyectos: Validador de Metodologías MRV', 'VI. Proyectos: MRV Methodologies Validator', 'Ayuda a elegir el método correcto para medir, reportar y verificar el impacto según el estándar internacional.', 'Helps choose correct MRV method based on international standards.', 'CheckSquare', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for MRV Methodologies Validator'),
('monitor-convocatorias', 'VI. Proyectos: Monitor de Convocatorias Internacionales', 'VI. Proyectos: International Grants Monitor', 'Filtra y alerta sobre fondos no reembolsables y licitaciones de organismos como el BID, BM o agencias de cooperación.', 'Alerts on grants and bids from BID, WB, or cooperation agencies.', 'Search', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for International Grants Monitor'),
('analizador-riesgo-ejec', 'VI. Proyectos: Analizador de Riesgo de Ejecución', 'VI. Proyectos: Execution Risk Analyzer', 'Identifica cuellos de botella técnicos o sociales que podrían hacer que un proyecto ambiental fracase antes de completarse.', 'Identifies bottlenecks that could fail an eco project mid-way.', 'AlertTriangle', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Execution Risk Analyzer'),
('gestor-app', 'VI. Proyectos: Gestor de Alianzas Público-Privadas', 'VI. Proyectos: PPP Alliance Manager', 'Estructura modelos de colaboración donde el gobierno pone el marco legal y la empresa privada la tecnología de impacto.', 'Structures PPP models combining gov legal frame with private tech.', 'Handshake', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for PPP Alliance Manager'),
('buscador-inversionistas', 'VI. Proyectos: Buscador de Inversionistas de Impacto', 'VI. Proyectos: Impact Investors Finder', 'Conecta proyectos verificados con Angel Investors o fondos de capital de riesgo que buscan retorno ambiental y financiero.', 'Connects verified projects with Impact Angel Investors.', 'Users', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Impact Investors Finder'),
('huella-proyecto', 'VI. Proyectos: Calculadora de Huella de Proyecto', 'VI. Proyectos: Project Footprint Calculator', 'Estima cuántas emisiones generará construir el proyecto mismo, para asegurar que el beneficio final sea mayor al costo inicial.', 'Estimates project construction emissions vs final benefit.', 'Wind', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Project Footprint Calculator'),
('disenador-kpis', 'VI. Proyectos: Diseñador de KPIs Ambientales', 'VI. Proyectos: Environmental KPIs Designer', 'Genera los indicadores clave de desempeño que los financiadores exigen ver en los reportes mensuales de avance.', 'Generates key performance indicators demanded by financiers.', 'Target', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Environmental KPIs Designer'),
('certificador-impacto', 'VI. Proyectos: Certificador de Impacto Verificable', 'VI. Proyectos: Verifiable Impact Certifier', 'Organiza la documentación necesaria para que una entidad externa (EVA) emita un certificado de cumplimiento sin errores.', 'Organizes docs for error-free external compliance certification.', 'Award', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Verifiable Impact Certifier'),
('simulador-precios', 'VI. Proyectos: Simulador de Precios de Activos Ambientales', 'VI. Proyectos: Eco Asset Price Simulator', 'Proyecta cuánto podría valer en el mercado un activo generado por el proyecto (ej. una unidad UCAM).', 'Projects future market value of project-generated assets.', 'DollarSign', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Eco Asset Price Simulator'),
('analizador-social', 'VI. Proyectos: Analizador de Co-beneficios Sociales', 'VI. Proyectos: Social Co-benefits Analyzer', 'Mide los impactos positivos extra, como creación de empleo local o mejora de la salud comunitaria.', 'Measures extra positive impacts like local jobs or community health.', 'Heart', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Social Co-benefits Analyzer'),
('cronograma-transicion', 'VI. Proyectos: Cronograma de Transición Sistémica', 'VI. Proyectos: Systemic Transition Timeline', 'Crea una hoja de ruta paso a paso para que un proyecto pase de ser una idea voluntaria a ser parte de la infraestructura del negocio.', 'Creates step-by-step roadmap to integrate voluntary ideas into infrastructure.', 'Calendar', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Systemic Transition Timeline'),
('hogar-sano', 'VII. Segmentos: Hogar Sano', 'VII. Segmentos: Healthy Home', 'Una app para familias que evalúa la salud de la casa. Escanea productos de limpieza, mide riesgos de moho y disruptores endocrinos.', 'Family app evaluating home health, scanning products, and mold risks.', 'Home', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Healthy Home'),
('corp-eco-manager', 'VII. Segmentos: Corporate Eco-Manager', 'VII. Segmentos: Corporate Eco-Manager', 'El tablero de control para el gerente de sostenibilidad. Centraliza la huella de carbono, gestiona residuos y genera reportes ESG.', 'Sustainability manager dashboard for footprint, waste, and ESG reports.', 'Briefcase', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Corporate Eco-Manager'),
('comunidad-circular', 'VII. Segmentos: Comunidad Circular', 'VII. Segmentos: Circular Community', 'Herramienta para barrios que organiza el intercambio de residuos, coordina rutas de reciclaje y mide el impacto positivo colectivo.', 'Neighborhood tool for waste exchange and communal recycling routes.', 'Users', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Circular Community'),
('eco-campus', 'VII. Segmentos: Eco-Campus', 'VII. Segmentos: Eco-Campus', 'Una plataforma que convierte el campus en un laboratorio vivo. Permite medir el consumo energético y gestionar el compost escolar.', 'Turns campus into a living lab for energy tracking and school compost.', 'BookOpen', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Eco-Campus'),
('gov-impact-mon', 'VII. Segmentos: Gov-Impact Monitor', 'VII. Segmentos: Gov-Impact Monitor', 'Diseñada para alcaldías. Permite monitorear metas climáticas, gestionar licencias ambientales y visualizar riesgos sanitarios.', 'Mayoralty app to monitor climate goals and visualize health risks.', 'Landmark', '[{"name": "input", "type": "textarea", "label_es": "Describe tu necesidad", "label_en": "Describe your need", "required": true}]'::jsonb, '[]'::jsonb, 'GENERAL INSTRUCTIONS: You are an expert Environmental Consultant. Respond in {{responseLanguage}}. Task: Process {{input}} for Gov-Impact Monitor')
ON CONFLICT (slug) DO UPDATE SET
  name_es = EXCLUDED.name_es,
  name_en = EXCLUDED.name_en,
  description_es = EXCLUDED.description_es,
  description_en = EXCLUDED.description_en,
  icon = EXCLUDED.icon,
  form_schema = EXCLUDED.form_schema,
  prompt_template = EXCLUDED.prompt_template;


-- Vinculación de Apps a Planes

-- 1. Primero, asegurarse de que los planes existan según la nueva estructura
DELETE FROM plans;


INSERT INTO plans (slug, name_es, name_en, description_es, description_en, price_monthly, app_limit, sort_order)
VALUES 
  ('gratis', 'Gratuito', 'Free', '5 Apps maestras pre-asignadas (familia, empresas, etc.).', '5 pre-assigned master apps (family, corporate, etc.).', 0, 5, 1),
  ('crecimiento-10', 'Crecimiento Inicial', 'Initial Growth', 'Desbloquea 10 apps adicionales a tu elección.', 'Unlocks 10 additional apps of your choice.', 27, 15, 2),
  ('crecimiento-30', 'Crecimiento Pro', 'Pro Growth', 'Desbloquea 30 apps a tu elección.', 'Unlocks 30 apps of your choice.', 47, 30, 3),
  ('crecimiento-max', 'Crecimiento Max', 'Max Growth', 'Desbloquea 60 apps a tu elección.', 'Unlocks 60 apps of your choice.', 97, 60, 4),
  ('elite', 'Plan Elite', 'Elite Plan', 'Desbloquea 80 apps a tu elección.', 'Unlocks 80 apps of your choice.', 197, 80, 5),
  ('master', 'Plan Master', 'Master Plan', 'Desbloqueo Ilimitado (120 apps).', 'Unlimited Unlock (120 apps).', 497, 120, 6)
ON CONFLICT (slug) DO UPDATE SET 
  name_es = EXCLUDED.name_es, 
  name_en = EXCLUDED.name_en, 
  price_monthly = EXCLUDED.price_monthly,
  app_limit = EXCLUDED.app_limit,
  description_es = EXCLUDED.description_es,
  description_en = EXCLUDED.description_en,
  sort_order = EXCLUDED.sort_order;

-- 2. Vincular Apps Demo del Segmento Maestro al Plan Gratuito (slug: gratis)
INSERT INTO plan_apps (plan_id, app_id)
SELECT p.id, m.id FROM plans p, micro_apps m 
WHERE p.slug = 'gratis' AND m.slug IN ('hogar-sano', 'corp-eco-manager', 'comunidad-circular', 'eco-campus', 'gov-impact-mon')
ON CONFLICT DO NOTHING;

-- 3. Vincular Todas las Apps a los demás planes (el desbloqueo lo limita app_limit en el backend)
INSERT INTO plan_apps (plan_id, app_id)
SELECT p.id, m.id FROM plans p, micro_apps m 
WHERE p.slug IN ('crecimiento-10', 'crecimiento-30', 'crecimiento-max', 'elite', 'master')
ON CONFLICT DO NOTHING;
