-- ===========================================================================
-- CLASIFICACIÓN DE LAS FICHAS QUE YA ESTÁN EN LA BIBLIOTECA
--
-- Pone el mapa sobre las 412 fichas sembradas: quién pone la plata y hasta
-- dónde llega. Se clasificó por reglas sobre el nombre, la línea temática y
-- el dominio del sitio oficial (.gov.co es Estado, .int y un.org son ONU,
-- .edu es academia, y así). Lo que no se pudo determinar queda como
-- 'por_clasificar' en vez de adivinarse.
--
-- Solo escribe donde todavía no hay clasificación: si el equipo ya corrigió
-- una ficha a mano, no se la pisa.
--
-- Requiere haber corrido antes supabase_migration_mapa.sql
-- ===========================================================================

UPDATE public.biblioteca_convocatorias AS b
SET tipo_financiador = CASE WHEN b.tipo_financiador = 'por_clasificar' THEN v.tipo ELSE b.tipo_financiador END,
    ambito           = CASE WHEN b.ambito = 'por_definir'              THEN v.ambito ELSE b.ambito END,
    actualizado_en   = now()
FROM (VALUES
  ('fundacion gates|', 'filantropia_privada', 'internacional'),
  ('wellcome trust|', 'filantropia_privada', 'internacional'),
  ('mastercard foundation|', 'filantropia_corporativa', 'regional'),
  ('instituto medico howard hughes|', 'filantropia_privada', 'nacional'),
  ('fundacion ford|', 'filantropia_privada', 'internacional'),
  ('fundacion novo nordisk|', 'filantropia_privada', 'internacional'),
  ('fundacion robert wood johnson rwjf|', 'filantropia_corporativa', 'por_definir'),
  ('fundacion familia walton|', 'filantropia_privada', 'por_definir'),
  ('tata trusts|', 'filantropia_privada', 'internacional'),
  ('silicon valley community foundation svcf|', 'filantropia_privada', 'municipal'),
  ('open society foundations|', 'onu', 'regional'),
  ('fundacion garfield weston|', 'onu', 'por_definir'),
  ('bloomberg philanthropies|', 'filantropia_corporativa', 'internacional'),
  ('wk kellogg foundation|', 'onu', 'regional'),
  ('macarthur foundation|', 'filantropia_privada', 'internacional'),
  ('li ka shing foundation|', 'filantropia_privada', 'nacional'),
  ('fundacion david lucile packard|', 'filantropia_privada', 'por_definir'),
  ('fundacion beneficencia leona m harry b helmsley|', 'filantropia_privada', 'por_definir'),
  ('fundacion mellon|', 'estado_nacional', 'por_definir'),
  ('propais|', 'estado_nacional', 'nacional'),
  ('corporacion colombia internacional cci|', 'ong', 'nacional'),
  ('promotora comercio social|', 'ong', 'nacional'),
  ('ministerio comercio industria turismo mincit|', 'estado_nacional', 'nacional'),
  ('departamento nacional planeacion dnp|', 'estado_nacional', 'nacional'),
  ('procolombia|', 'estado_nacional', 'nacional'),
  ('corporacion minuto dios|', 'filantropia_privada', 'nacional'),
  ('oit organizacion internacional trabajo|', 'onu', 'nacional'),
  ('agrosolidaria|', 'estado_nacional', 'nacional'),
  ('federacion nacional municipios|', 'estado_local', 'municipal'),
  ('federacion nacional departamentos|', 'estado_local', 'nacional'),
  ('fundacion saldarriaga concha|', 'filantropia_privada', 'nacional'),
  ('agencia desarrollo rural adr|', 'estado_nacional', 'nacional'),
  ('organizacion internacional migraciones oim|', 'onu', 'nacional'),
  ('agencia renovacion territorio|', 'estado_nacional', 'nacional'),
  ('francisco jose caldas|', 'estado_nacional', 'nacional'),
  ('pago por resultados prosperidad social|', 'estado_nacional', 'nacional'),
  ('mujer emprende|', 'estado_nacional', 'nacional'),
  ('asomicrofinanzas|', 'empresa_privada', 'nacional'),
  ('francorp centroamerica|', 'empresa_privada', 'regional'),
  ('ministerio ciencia tecnologia e innovacion minciencias|', 'estado_nacional', 'nacional'),
  ('servicio nacional aprendizaje sena|', 'estado_nacional', 'nacional'),
  ('departamento prosperidad social dps|', 'estado_nacional', 'nacional'),
  ('banco interamericano desarrollo bid|', 'cooperacion_multilateral', 'nacional'),
  ('union europea|', 'cooperacion_multilateral', 'regional'),
  ('ministerio agricultura desarrollo rural madr|', 'estado_nacional', 'nacional'),
  ('unidad atencion reparacion integral a victimas|', 'estado_nacional', 'nacional'),
  ('nacional garantias fng|', 'banca_desarrollo', 'nacional'),
  ('fundacion capital fundak sucursal colombiana|', 'filantropia_privada', 'nacional'),
  ('cuso international|', 'cooperacion_bilateral', 'nacional'),
  ('fundacion plan internacional|', 'filantropia_privada', 'nacional'),
  ('fundacion panamericana desarrollo fupad|', 'filantropia_privada', 'nacional'),
  ('sibsco|', 'ong', 'nacional'),
  ('fao organizacion naciones unidas alimentacion agricultura|', 'onu', 'nacional'),
  ('banco agrario colombia|', 'banca_desarrollo', 'nacional'),
  ('agencia reincorporacion normalizacion arn|', 'estado_nacional', 'nacional'),
  ('finagro financiamiento sector agropecuario|', 'banca_desarrollo', 'nacional'),
  ('fundacion colombia incluyente|', 'filantropia_privada', 'nacional'),
  ('fundacion rofe|', 'filantropia_privada', 'nacional'),
  ('chemonics internacional|', 'empresa_privada', 'nacional'),
  ('banco mundial|', 'cooperacion_multilateral', 'nacional'),
  ('internacional desarrollo agricola fida|', 'cooperacion_multilateral', 'nacional'),
  ('global environment facility gef|', 'cooperacion_multilateral', 'nacional'),
  ('usaid agencia estados unidos desarrollo internacional|', 'onu', 'nacional'),
  ('fundacion rockefeller|', 'filantropia_privada', 'nacional'),
  ('corporacion andina fomento caf|', 'cooperacion_multilateral', 'nacional'),
  ('colombia en paz|', 'estado_nacional', 'nacional'),
  ('1000 suenos|', 'ong', 'nacional'),
  ('innovacion 100 000 strong in the americas|', 'ong', 'regional'),
  ('100 accelerator|', 'empresa_privada', 'internacional'),
  ('4humanities|', 'estado_nacional', 'nacional'),
  ('appace|', 'ong', 'nacional'),
  ('4a s foundation|', 'filantropia_privada', 'internacional'),
  ('fundacion fupad|', 'filantropia_privada', 'nacional'),
  ('fundacion muste|', 'filantropia_privada', 'internacional'),
  ('fundacion aci|', 'filantropia_privada', 'nacional'),
  ('fundacion alemana investigacion ev|', 'filantropia_privada', 'nacional'),
  ('fundacion aci medellin|', 'filantropia_privada', 'municipal'),
  ('agencia cooperacion internacional japon jica|', 'cooperacion_bilateral', 'nacional'),
  ('fundacion aldeas infantiles sos colombia|', 'filantropia_privada', 'nacional'),
  ('accion solidaria|', 'ong', 'nacional'),
  ('acicafoc|', 'ong', 'nacional'),
  ('ymca quindio|', 'ong', 'nacional'),
  ('acodea|', 'ong', 'nacional'),
  ('100k strong in the americas|', 'ong', 'por_definir'),
  ('fundacion 1000 hermanos|', 'filantropia_privada', 'nacional'),
  ('alert fund for youth|', 'por_clasificar', 'nacional'),
  ('access agriculture|', 'ong', 'nacional'),
  ('campus france|', 'ong', 'nacional'),
  ('jica agencia cooperacion internacional japon|', 'cooperacion_bilateral', 'nacional'),
  ('tika|', 'empresa_privada', 'nacional'),
  ('acnur|', 'onu', 'nacional'),
  ('aecid|', 'cooperacion_bilateral', 'nacional'),
  ('norad|', 'cooperacion_bilateral', 'regional'),
  ('slks|', 'por_clasificar', 'nacional'),
  ('sida|', 'cooperacion_bilateral', 'regional'),
  ('agora 2030|', 'ong', 'nacional'),
  ('agiamondo|', 'por_clasificar', 'nacional'),
  ('liderazgo en investigacion indigena conectando 2025|', 'por_clasificar', 'regional'),
  ('solicite estudios ucranianos lysiak rudnytsky|', 'ong', 'internacional'),
  ('se abren inscripciones necesidad urgente 2025|', 'ong', 'internacional'),
  ('periodismo covid 19 equidad global en salud|', 'ong', 'internacional'),
  ('subvenciones investigacion ignacio h larramendi 2025|', 'filantropia_privada', 'nacional'),
  ('a investigacion en salud global|', 'ong', 'internacional'),
  ('fortalecimiento estandares digitales europeos en lac|', 'filantropia_corporativa', 'internacional'),
  ('pequenas donaciones fortalecer filantropia comunitaria|', 'filantropia_privada', 'regional'),
  ('subvenciones proyectos sociales 2025 2026|', 'ong', 'nacional'),
  ('conectando saberes indigenas entre sur global canada|', 'por_clasificar', 'regional'),
  ('internacional proyectos sobre microbiota intestinal|', 'filantropia_privada', 'nacional'),
  ('financiacion centro global evidencia seguridad|', 'filantropia_privada', 'regional'),
  ('subvenciones preparacion proyectos ppg 2025 stdf|', 'ong', 'nacional'),
  ('solicitudes investigacion museo nacional zayed|', 'por_clasificar', 'nacional'),
  ('subvenciones fundacion lloyd s of london|', 'filantropia_privada', 'nacional'),
  ('subvenciones acustica vida silvestre 2025|', 'empresa_privada', 'por_definir'),
  ('subvenciones proyectos aplicacion normas fomento comercio stdf 2025|', 'ong', 'por_definir'),
  ('subvencion educacion superior interledger nextgen|', 'ong', 'internacional'),
  ('financiacion rainforest trust creacion areas protegidas o conservadas|', 'filantropia_privada', 'internacional'),
  ('unicef busca proximas herramientas edtech unicornio azul cerrar brechas globales aprendizaje|', 'onu', 'nacional'),
  ('generaciones global subvenciones|', 'estado_nacional', 'nacional'),
  ('subvenciones apoyo a eventos instituto estudios humanos|', 'ong', 'nacional'),
  ('subvenciones apoyo a gastos instituto estudios humanos|', 'ong', 'nacional'),
  ('beca fotoperiodismo ian parry 2025|', 'ong', 'nacional'),
  ('becas holohil|', 'empresa_privada', 'internacional'),
  ('comun productos basicos|', 'empresa_privada', 'regional'),
  ('proyectos stem sostenibles|', 'por_clasificar', 'nacional'),
  ('subvenciones a proyectos soluciones innovadoras|', 'por_clasificar', 'nacional'),
  ('biotecnologia 2025|', 'por_clasificar', 'internacional'),
  ('ernest solvay 2025|', 'por_clasificar', 'nacional'),
  ('subvenciones a proyectos d prize|', 'ong', 'nacional'),
  ('propuestas levante 2025|', 'ong', 'nacional'),
  ('the catalyst fund|', 'filantropia_privada', 'regional'),
  ('financiamiento mejoramiento vida|', 'filantropia_privada', 'internacional'),
  ('subvenciones elaboracion informes sobre aprendizaje automatico|', 'ong', 'internacional'),
  ('subvenciones innovacion social|', 'filantropia_privada', 'internacional'),
  ('asistencia financiera no reembolsable proyectos comunitarios kusanone 2025|', 'por_clasificar', 'nacional'),
  ('subvenciones impacto social en etapa inicial fundacion drk|', 'onu', 'regional'),
  ('financiacion a innovaciones que busquen acabar con pobreza|', 'ong', 'nacional'),
  ('apoyo respuesta rapida mujeres|', 'ong', 'regional'),
  ('libertad en internet|', 'por_clasificar', 'internacional'),
  ('proyectos apoyo patentamiento invenciones modelos utilidad|', 'ong', 'por_definir'),
  ('aldea b 24 asistencia tecnica emprendimientos innovadores|', 'estado_nacional', 'nacional'),
  ('sostenibilidad en mipymes turisticas|', 'estado_nacional', 'nacional'),
  ('innovacion en desarrollo fid|', 'por_clasificar', 'internacional'),
  ('titulo subvenciones a proyectos fundacion draper richards kaplan|', 'onu', 'regional'),
  ('biodiv world|', 'por_clasificar', 'internacional'),
  ('carbon to value initiative year 5 innovation cohort request for applications rfa|', 'onu', 'nacional'),
  ('mangrove positive businesses funding window bajo marco blue carbon plus bc|', 'ong', 'nacional'),
  ('mujer protegida|', 'estado_nacional', 'nacional'),
  ('amazonia por siempre|', 'filantropia_corporativa', 'regional'),
  ('innovacion global 2024|', 'por_clasificar', 'nacional'),
  ('concurso innovacion empresarial pequenas medianas empresas|', 'estado_nacional', 'nacional'),
  ('transformacion planeacion minero energetica convergencia territorial transicion energetica justa|', 'estado_nacional', 'nacional'),
  ('iniciativa clima cuidado|', 'ong', 'regional'),
  ('incentivos jovenes investigadores en investigacion caminos atencion integrada abordar ent condiciones salud mental|', 'onu', 'internacional'),
  ('caja impacto|', 'ong', 'internacional'),
  ('accion acceso seguro al aborto|', 'ong', 'internacional'),
  ('amazonia|', 'filantropia_corporativa', 'nacional'),
  ('innovacion tecnologia codigo abierto|', 'onu', 'internacional'),
  ('tematica iki 2024|', 'empresa_privada', 'internacional'),
  ('iniciativa bluetech residuos|', 'empresa_privada', 'por_definir'),
  ('fit4future fase ii|', 'filantropia_privada', 'nacional'),
  ('senainnova 2024 fomentar acceso adopcion tecnologias avanzadas en sector agroalimentario hacia sistemas soberanos|', 'estado_nacional', 'nacional'),
  ('grandes retos produccion accesible anticuerpos monoclonales|', 'ong', 'regional'),
  ('juntanza por diversidad laboral etnica|', 'ong', 'nacional'),
  ('subvenciones copatrocinio otan|', 'por_clasificar', 'internacional'),
  ('subvenciones organizacion comunitaria|', 'onu', 'nacional'),
  ('crypto for good iv|', 'empresa_privada', 'internacional'),
  ('tecnologia resiliencia comunitaria|', 'filantropia_privada', 'internacional'),
  ('global investigacion en enfermedades dermatologicas|', 'filantropia_privada', 'internacional'),
  ('investigacion operativa sobre resistencia|', 'por_clasificar', 'internacional'),
  ('bluetech residuos|', 'empresa_privada', 'regional'),
  ('horizonte europa marco innovacion|', 'cooperacion_multilateral', 'regional'),
  ('subvencion reinforcing sobre digitalizacion responsable|', 'cooperacion_multilateral', 'por_definir'),
  ('financiacion innovacion escalables desde etapa prototipo hasta su escalibilidad|', 'por_clasificar', 'internacional'),
  ('subvencion desarrollo comunitario|', 'estado_nacional', 'regional'),
  ('promover competitividad diversificacion economica agricola no agricola tipo anual aps numero set aps 2024 001|', 'empresa_privada', 'nacional'),
  ('subvenciones institucionales|', 'filantropia_privada', 'internacional'),
  ('darwin intiative extra|', 'ong', 'internacional'),
  ('darwin intiative|', 'ong', 'internacional'),
  ('darwin initiative capability capacity|', 'ong', 'internacional'),
  ('desafio contra comercio ilegal vida silvestre iwt|', 'ong', 'internacional'),
  ('fortaleser|', 'cooperacion_bilateral', 'municipal'),
  ('nacional apoyo a innovacion empresarial|', 'banca_desarrollo', 'nacional'),
  ('economia popular pesca artesanal una herencia que fluye|', 'empresa_privada', 'nacional'),
  ('paz sembrando oportunidades cosechando futuro emprender no 113 pdet pnis|', 'estado_nacional', 'nacional'),
  ('seleccion mipymes participantes en encadena mejores proveedores cadena valor astilleros embarcaciones menores|', 'empresa_privada', 'nacional'),
  ('conectadods 2024|', 'por_clasificar', 'por_definir'),
  ('stem doc 2024|', 'por_clasificar', 'por_definir'),
  ('opec fund grant program|', 'ong', 'nacional'),
  ('proyecto vida empleabilidad emprendimiento jovenes|', 'filantropia_privada', 'nacional'),
  ('validacion innovacion pequenas medianas empresas|', 'estado_nacional', 'nacional'),
  ('ella invierte|', 'estado_nacional', 'nacional'),
  ('ella invierte inversionistas|', 'estado_nacional', 'nacional'),
  ('industrias culturales creativas ancestrales no 118|', 'empresa_privada', 'nacional'),
  ('ecoturismo no 117|', 'empresa_privada', 'nacional'),
  ('emprendimiento verde no 116|', 'empresa_privada', 'nacional'),
  ('jovenes crea tu futuro no 115|', 'empresa_privada', 'nacional'),
  ('nacional emprender no 112 economia campesina|', 'estado_nacional', 'nacional'),
  ('cadenas valor 4 0|', 'empresa_privada', 'nacional'),
  ('seleccion mipymes unidades productivas beneficiarias asesoria grupal en instrumentos promover su encadenamiento productivo|', 'empresa_privada', 'nacional'),
  ('reto 6 convergencia regional ordenamiento territorial|', 'estado_nacional', 'nacional'),
  ('asignacion ciencia tecnologia e innovacion sistema general regalias agroecologia sostenibilidad|', 'estado_nacional', 'nacional'),
  ('desarrollo ecosistemas investigacion e innovacion transicion energetica justa|', 'estado_nacional', 'nacional'),
  ('conformacion un listado proyectos elegibles que contribuyan a erradicacion violencia|', 'estado_nacional', 'nacional'),
  ('sectorial educacion modalidad inclusion digital educacion con nuevos horizontes|', 'cooperacion_multilateral', 'por_definir'),
  ('desarrollo tecnologias desde consorcios cadenas valor|', 'estado_nacional', 'nacional'),
  ('verde catalitico|', 'cooperacion_multilateral', 'regional'),
  ('subvenciones catalyst|', 'ong', 'regional'),
  ('reto 1 aprovechar conocimiento conservacion uso sostenible biodiversidad bienes servicios ecosistemicos|', 'estado_nacional', 'nacional'),
  ('innovacion empresarial fase 1|', 'estado_nacional', 'nacional'),
  ('fondos capital riesgo bid lab|', 'cooperacion_multilateral', 'regional'),
  ('p4g creacion alianzas|', 'ong', 'nacional'),
  ('primer donaciones comunitarias energia solar subvenciones participacion civica impacto ambiental donacion modulos|', 'onu', 'regional'),
  ('piedemonte amazonico facnnm|', 'filantropia_corporativa', 'nacional'),
  ('titulo ideas grandes audaces un futuro mejor|', 'filantropia_privada', 'regional'),
  ('canadiense iniciativas locales salvador 2025|', 'por_clasificar', 'internacional'),
  ('protected or conserved area creation awards|', 'filantropia_privada', 'internacional'),
  ('reto innovacion abierta en sostenibilidad|', 'por_clasificar', 'internacional'),
  ('canadiense iniciativas locales en ecuador cfli|', 'por_clasificar', 'nacional'),
  ('titulo historias climaticas 2025|', 'ong', 'nacional'),
  ('subvenciones vision|', 'ong', 'nacional'),
  ('innovacion bienestar juvenil fit4future|', 'filantropia_privada', 'internacional'),
  ('estudios desarrollo infantil 2024|', 'ong', 'internacional'),
  ('ventana adelante cooperacion triangular|', 'cooperacion_multilateral', 'regional'),
  ('blue unicorn farm|', 'onu', 'internacional'),
  ('proyectos salud mental en ninos jovenes|', 'por_clasificar', 'nacional'),
  ('medallas premios royal society 2025|', 'academia', 'nacional'),
  ('apoyo a sociedad civil respuestas transformadoras contra tuberculosis|', 'ong', 'nacional'),
  ('salud movil tecnologia resultados en paises ingresos bajos medios r21 r33 ensayo clinico opcional|', 'estado_nacional', 'regional'),
  ('financiamiento investigacion en ia cooperacion global|', 'empresa_privada', 'internacional'),
  ('innovacion climatica positiva con biodiversidad|', 'ong', 'internacional'),
  ('riesgo unicef soluciones tecnologicas innovadoras|', 'onu', 'internacional'),
  ('11 propuestas isf|', 'ong', 'por_definir'),
  ('residencia investigacion en archivos fundacion robert rauschenberg|', 'filantropia_privada', 'internacional'),
  ('tefaf museum restoration fund tmrf 2025|', 'filantropia_privada', 'internacional'),
  ('innovacion juvenil sistemas agroalimentarios sostenibles solicitudes subvenciones cag 2024|', 'filantropia_privada', 'internacional'),
  ('financiamiento proyectos conservacion ambiental|', 'ong', 'internacional'),
  ('concurso subvenciones 100k strong united states colombia|', 'ong', 'nacional'),
  ('grants fundacion van tienhoven|', 'filantropia_privada', 'regional'),
  ('maestros no pueden esperar|', 'academia', 'por_definir'),
  ('twas atta ur rahman en quimica|', 'ong', 'por_definir'),
  ('colombia ee uu 100 000 strong in the americas|', 'onu', 'nacional'),
  ('investigacion educacion en horticultura ornamental|', 'ong', 'regional'),
  ('subvenciones investigacion preclinica traslacional integrina beta 6 ib6 sigvotatig vedotin sv|', 'filantropia_corporativa', 'internacional'),
  ('reto innovea finanzas manana|', 'empresa_privada', 'internacional'),
  ('subvenciones asociacion ocean soluciones escalables|', 'empresa_privada', 'internacional'),
  ('financiacion clasico developpp|', 'por_clasificar', 'por_definir'),
  ('financiacion conectar a desconectados|', 'ong', 'nacional'),
  ('subvenciones barakat trus|', 'ong', 'nacional'),
  ('subvenciones instituto estudios anarquistas agencias 2024 25|', 'ong', 'nacional'),
  ('facilidad solnatura promoviendo soluciones basadas en naturaleza un desarrollo territorial resiliente bajo en carbono biodiverso|', 'ong', 'nacional'),
  ('mundial subvenciones investigacion cancer|', 'ong', 'internacional'),
  ('financiamiento proyectos soluciones basadas en naturaleza en cordoba huila santander|', 'filantropia_corporativa', 'departamental'),
  ('propuestas comun productos basicos|', 'empresa_privada', 'internacional'),
  ('impact and innovation in commodity value chains|', 'empresa_privada', 'por_definir'),
  ('becas investigacion fundacion leo|', 'filantropia_privada', 'nacional'),
  ('becas investigacion twas en ciencias basicas grupos|', 'cooperacion_multilateral', 'por_definir'),
  ('iniciativas arte participativo proteccion agua|', 'por_clasificar', 'nacional'),
  ('premios descubrimiento wellcome|', 'onu', 'regional'),
  ('financiacion fundacion alstom|', 'filantropia_privada', 'por_definir'),
  ('resiliencia a traves seguro inclusivo|', 'empresa_privada', 'nacional'),
  ('impulsando sostenibilidad sistemas agroalimentarios en america latina caribe|', 'cooperacion_multilateral', 'regional'),
  ('cfas fortalecimiento enfoque gestion basado en ecosistemas|', 'ong', 'internacional'),
  ('desafio innovacion resiliencia urbana|', 'ong', 'internacional'),
  ('becas investigacion copper clm|', 'ong', 'regional'),
  ('financiamiento proyectos agroalimentarios sostenibles|', 'cooperacion_multilateral', 'regional'),
  ('subvenciones tecnologicas echo360 e3|', 'empresa_privada', 'nacional'),
  ('desafio comunicacion inclusiva impulsada por ia|', 'ong', 'internacional'),
  ('fiat ifta media studies grant 2025|', 'ong', 'nacional'),
  ('desafio innovacion generar impacto|', 'ong', 'internacional'),
  ('financiamiento investigacion en salud mental|', 'filantropia_privada', 'internacional'),
  ('innovacion tecnologica en salud global|', 'academia', 'internacional'),
  ('innovacion prosperidad economica|', 'academia', 'internacional'),
  ('mit solve soluciones tecnologicas educacion aprendizaje|', 'academia', 'internacional'),
  ('centro estudios ibericos 2025|', 'por_clasificar', 'internacional'),
  ('narracion historias sobre agua dulce|', 'ong', 'internacional'),
  ('agrip simple|', 'cooperacion_multilateral', 'regional'),
  ('promocion productos agricolas ue|', 'cooperacion_multilateral', 'regional'),
  ('apoyo a expresiones culturales artisticas personas con discapacidad en bogota|', 'estado_nacional', 'municipal'),
  ('financiamiento proyectos culturales mujeres bogotanas|', 'estado_nacional', 'municipal'),
  ('turismo indigena desarrollo sostenible|', 'ong', 'regional'),
  ('proyectos sobre impacto cambio climatico en salud|', 'filantropia_privada', 'internacional'),
  ('l oreal organizaciones primera linea mujeres 2025|', 'filantropia_corporativa', 'nacional'),
  ('subvenciones ambientales 2025|', 'filantropia_privada', 'nacional'),
  ('pequenas subvenciones fortalecer datos sobre fortificacion alimentos|', 'ong', 'nacional'),
  ('global subvenciones cientificos|', 'filantropia_privada', 'nacional'),
  ('premios sobre impacto climatico|', 'filantropia_privada', 'nacional'),
  ('subvencion empresarial iccbba 2025|', 'ong', 'nacional'),
  ('macroproyectos nacionales financiacion innovacion conservacion ambiental|', 'estado_nacional', 'nacional'),
  ('innovaciones sostenibles wash|', 'onu', 'internacional'),
  ('subvencion impacto global|', 'filantropia_privada', 'regional'),
  ('tecnologia innovadora seguridad hidrica|', 'empresa_privada', 'nacional'),
  ('adquisicion tierras uicn paises bajos|', 'ong', 'regional'),
  ('pensamiento espacial inspirar accion a traves subvenciones soluciones basadas en lugar|', 'ong', 'internacional'),
  ('gestion integrada salud cuencas|', 'ong', 'internacional'),
  ('pequenas subvenciones global forest watch 2025|', 'ong', 'nacional'),
  ('subvencion contra violencia digital hack everything|', 'ong', 'nacional'),
  ('grandes subvenciones investigacion en educacion 2025|', 'ong', 'regional'),
  ('semana negroni slow food|', 'empresa_privada', 'nacional'),
  ('subvenciones investigacion proteinas alternativas gfi|', 'ong', 'internacional'),
  ('innovacion en agencia humana|', 'por_clasificar', 'regional'),
  ('subvenciones educacion medica independientes optimizar tratamiento cancer mama metastasico er|', 'filantropia_corporativa', 'nacional'),
  ('subvenciones productos cientificos acustica vida silvestre 2025|', 'empresa_privada', 'nacional'),
  ('cooperacion en ciencia tecnologia e innovacion|', 'cooperacion_multilateral', 'nacional'),
  ('soluciones financiacion youth4climate apoyar a jovenes|', 'por_clasificar', 'nacional'),
  ('implementacion piloto discapacidad cuidado en villavicencio colombia|', 'ong', 'nacional'),
  ('subvenciones ambientales ford 2025|', 'empresa_privada', 'por_definir'),
  ('al invest green 2025|', 'cooperacion_multilateral', 'regional'),
  ('cfas tecnologias apoyo ampliacion terapias reemplazo islotes manufacturados|', 'ong', 'internacional'),
  ('oportunidad financiamiento directo jovenes lideres en temas climaticos|', 'por_clasificar', 'internacional'),
  ('subvenciones ecosistema cesio|', 'empresa_privada', 'internacional'),
  ('retos innovacion|', 'estado_nacional', 'nacional'),
  ('mejores proveedores productos servicios con minerales estrategicos|', 'empresa_privada', 'nacional'),
  ('centro reindustrializacion zasca tecnologias antioquia|', 'estado_nacional', 'departamental'),
  ('bid femsa 2024|', 'filantropia_corporativa', 'regional'),
  ('premios fundacion mapfre a innovacion social octava edicion|', 'filantropia_privada', 'regional'),
  ('the audacious project|', 'ong', 'por_definir'),
  ('the liveability challenge 2025|', 'ong', 'internacional'),
  ('development innovation ventures div|', 'cooperacion_bilateral', 'internacional'),
  ('p4g presentacion solicitudes colaboracion|', 'ong', 'regional'),
  ('fit4future financiamiento propuestas innovadoras|', 'ong', 'nacional'),
  ('subvencion fundacion cultura animales|', 'filantropia_privada', 'nacional'),
  ('propuestas apoyo a una transicion rural justa 2025|', 'estado_nacional', 'internacional'),
  ('fundacion bayer a mujeres emprendedoras 2025|', 'filantropia_corporativa', 'internacional'),
  ('apoyo a productos seguros contra riesgos climaticos|', 'ong', 'regional'),
  ('cooperacion financiera no reembolsable|', 'por_clasificar', 'por_definir'),
  ('pequenas subvenciones iki|', 'por_clasificar', 'nacional'),
  ('solicitar una subvencion desarrollo comunitario|', 'estado_nacional', 'nacional'),
  ('google org accelerator generative ai|', 'filantropia_corporativa', 'internacional'),
  ('asistencia financiera no reembolsable proyectos comunitarios seguridad humana kusanone|', 'por_clasificar', 'nacional'),
  ('canada iniciativas locales argentina 2025 26|', 'cooperacion_bilateral', 'nacional'),
  ('subvenciones asociaciones subvenciones asociacion ocean soluciones escalables|', 'cooperacion_multilateral', 'nacional'),
  ('donacion stdf preparacion proyectos|', 'ong', 'por_definir'),
  ('fundacion mitsubishi corporation americas mcfa|', 'filantropia_privada', 'por_definir'),
  ('technologies with untapped potential scaleup ready|', 'estado_nacional', 'por_definir'),
  ('soluciones climaticas inteligentes nature smart|', 'filantropia_corporativa', 'por_definir'),
  ('abierta climatico ekoenergia|', 'ong', 'por_definir'),
  ('wellcome discovery awards|', 'onu', 'regional'),
  ('declaracion anual diplomacia publica embajada estados unidos en santiago|', 'onu', 'nacional'),
  ('multistakeholder engagement for safe and prosperous ai|', 'ong', 'internacional'),
  ('the fund for innovation in development|', 'por_clasificar', 'internacional'),
  ('proyectos carbon 2025 agua dulce|', 'ong', 'por_definir'),
  ('zayed a sostenibilidad|', 'empresa_privada', 'internacional'),
  ('solicitud notas conceptuales avanzar en investigacion sobre salud sexual reproductiva adolescentes|', 'onu', 'por_definir'),
  ('desafio solve|', 'academia', 'internacional'),
  ('research grants on education small|', 'ong', 'internacional'),
  ('merck research grants 2025|', 'empresa_privada', 'internacional'),
  ('connecting the unconnected funding program|', 'ong', 'internacional'),
  ('united nations democracy fund undef 19th round of funding|', 'onu', 'por_definir'),
  ('innovative data and modeling approaches to measure women s health rfp grand challenges|', 'filantropia_privada', 'por_definir'),
  ('grants for the production dissemination and exhibition of contemporary art in denmark and abroad note prepare the required attachments and read the application guide before starting your application see what the application must include to c|', 'por_clasificar', 'por_definir'),
  ('movilidad themis|', 'por_clasificar', 'internacional'),
  ('usf seminar series awards 2024 2025|', 'filantropia_privada', 'internacional'),
  ('cisco liderazgo juvenil global|', 'ong', 'internacional'),
  ('mopga 2025 becas visita investigadores en inicio su carrera|', 'por_clasificar', 'internacional'),
  ('beca ksj mit 2025 2026|', 'empresa_privada', 'internacional'),
  ('licitacion publica alcantarillado en barrio faustino mojica|', 'cooperacion_bilateral', 'nacional'),
  ('innovacion climatica curva keeling|', 'ong', 'internacional'),
  ('abordar deficiencias en atencion mieloma multiple en pacientes america latina|', 'filantropia_corporativa', 'regional'),
  ('fotografia wellcome 2025|', 'filantropia_privada', 'internacional'),
  ('premios harry frank guggenheim academicos emergentes|', 'ong', 'internacional'),
  ('empleabilidad paz bienestar sostenibilidad|', 'cooperacion_multilateral', 'regional'),
  ('innovacion wald|', 'ong', 'regional'),
  ('solicitudes subvenciones centradas en selva tropical oceano transparencia|', 'academia', 'por_definir'),
  ('competencia global innovacion emprendimiento|', 'ong', 'internacional'),
  ('financiar soluciones basadas en naturaleza|', 'por_clasificar', 'nacional'),
  ('subvencionar iniciativas alineadas con siguientes tematicas cambio climatico agroecologia naturaleza urbana diversidad cultural pesca a pequena escala|', 'por_clasificar', 'nacional'),
  ('acelerar ambiciones stem espaciales 2025 luxemburgo|', 'estado_nacional', 'por_definir'),
  ('educacion digital uso etico eficaz sistemas ia generativa en educacion formacion|', 'cooperacion_multilateral', 'por_definir'),
  ('research grants 2025|', 'empresa_privada', 'por_definir'),
  ('innovative climate with biodiversity positive projects|', 'ong', 'por_definir'),
  ('subvenciones vision fundacion spencer|', 'filantropia_privada', 'por_definir'),
  ('subvenciones fit4future fase 2|', 'filantropia_privada', 'por_definir'),
  ('desafio seeding the future global food system challenge|', 'ong', 'internacional'),
  ('fundacion conservacion alimentacion salud|', 'filantropia_privada', 'por_definir'),
  ('subvenciones svenska postkod lotteriet|', 'por_clasificar', 'por_definir'),
  ('respuesta rapida mujer paz seguridad|', 'ong', 'por_definir'),
  ('creacion apoyo a una comunidad actores no estatales participar en reforma politicas agricolas reutilizacion subsidios|', 'estado_nacional', 'internacional'),
  ('sexta propuestas pequenas subvenciones iki|', 'por_clasificar', 'por_definir'),
  ('transformacion climatica 2025|', 'empresa_privada', 'por_definir'),
  ('wilkes climate launch 2025|', 'academia', 'por_definir'),
  ('civic engagement and environmental impact grants module donation program|', 'ong', 'por_definir'),
  ('horizonte europa eficiencia recursos energia fotovoltaica en produccion uso eliminacion|', 'cooperacion_multilateral', 'regional'),
  ('desafio 2025 sistema alimentario mundial sembrando futuro|', 'ong', 'internacional'),
  ('donaciones preparacion proyectos ppg|', 'cooperacion_multilateral', 'por_definir'),
  ('desafio ebbe nielsen 2025|', 'por_clasificar', 'nacional'),
  ('garden grants biotecnologia eliminacion gases efecto invernadero|', 'por_clasificar', 'nacional'),
  ('desafio innovacion global acelerar empleabilidad jovenes|', 'filantropia_privada', 'internacional'),
  ('subvenciones investigacion lcrf superar resistencia en cancer pulmon|', 'filantropia_privada', 'internacional'),
  ('mohamed bin zayed conservacion especies|', 'por_clasificar', 'internacional'),
  ('subvenciones stanley smith horticultural trust|', 'filantropia_privada', 'regional'),
  ('desafio puesta en marcha carboncapture|', 'por_clasificar', 'internacional'),
  ('desarrollo capacidades en efp america latina|', 'cooperacion_multilateral', 'regional'),
  ('fortalecimiento capacidades en educacion formacion tecnica profesional|', 'cooperacion_multilateral', 'regional'),
  ('iniciativas divulgacion proyectos evolucion|', 'por_clasificar', 'internacional'),
  ('naciones unidas democracia undef|', 'onu', 'internacional'),
  ('campeones pequenas empresas grupo pyme icc icc omc 2025|', 'por_clasificar', 'internacional'),
  ('desarrollo profesional minorias cda en cancer pulmon|', 'filantropia_privada', 'internacional'),
  ('subvenciones incubacion fundacion mito|', 'filantropia_privada', 'nacional'),
  ('subvenciones padres ibro|', 'por_clasificar', 'nacional'),
  ('transformacion cadenas valor|', 'por_clasificar', 'internacional'),
  ('green fellows 2025|', 'por_clasificar', 'internacional'),
  ('respuesta rapida sur global|', 'por_clasificar', 'internacional'),
  ('donaciones fundacion interamericana iaf|', 'filantropia_privada', 'regional'),
  ('empresas innovacion desarrollo div|', 'onu', 'nacional'),
  ('a innovacion en economia circular pequenas empresas|', 'por_clasificar', 'internacional'),
  ('subvenciones investigacion vanguardia lcrf|', 'filantropia_privada', 'internacional'),
  ('asociaciones p4g negocios climaticos|', 'ong', 'internacional'),
  ('sena innova 2025|', 'estado_nacional', 'nacional'),
  ('especialistas en salud|', 'por_clasificar', 'regional'),
  ('subvenciones mes concientizacion sobre cancer vejiga|', 'por_clasificar', 'regional'),
  ('mundial ayuda pescadores igfa warf|', 'ong', 'nacional'),
  ('iniciativa difusion eseb|', 'por_clasificar', 'nacional')
) AS v(clave, tipo, ambito)
WHERE b.clave = v.clave;
