import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { guardarEnBiblioteca, type ConvocatoriaEncontrada } from '@/lib/bibliotecaConvocatorias'
import { motorAutorizado } from '@/lib/candadoMotores'

/**
 * CENTINELA — siembra puntual del boletín "Convocatorias-No-Reembolsables-
 * Propulsa-2026-09-20.pdf" que Gonzalo subió el 26 de sep de 2026.
 *
 * Este boletín no llegó por Gmail (no es una Alerta de Google ni un correo):
 * es un PDF de 25 páginas con 40 convocatorias ya verificadas en su fuente
 * oficial por quien armó el consolidado, con corte al 20 de septiembre de
 * 2026. En vez de hacerle gastar cuota de Gemini analizando de nuevo cada
 * enlace, las 40 fichas se transcribieron a mano del PDF y se guardan aquí
 * directo en la misma biblioteca que usa el Motor 2 — con la misma función
 * `guardarEnBiblioteca`, así que si alguna ya existía (por nombre+entidad)
 * solo se completan los huecos, nunca se pisa lo que el equipo ya corrigió.
 *
 * Es una ruta de un solo uso: se visita una vez desde el navegador (con
 * sesión del equipo Serving iniciada) para sembrar las 40, y no hace falta
 * volver a llamarla — no hay nada que repetir automáticamente, a diferencia
 * de /api/centinela/leer-alertas que sí corre todos los días.
 */

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
)

const CONVOCATORIAS_PROPULSA: ConvocatoriaEncontrada[] = [
  {
    nombre: 'Council on Australia Latin America Relations (COALAR) Grants Program 2026-2027',
    entidad: 'Department of Foreign Affairs and Trade (DFAT), Gobierno de Australia',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-09-21 (12:00 AEST)',
    fecha_cierre: '2026-09-21',
    monto: 'AUD 15.000 a 50.000 por proyecto; bolsa total de hasta AUD 300.000',
    beneficiarios: 'Organizaciones de países latinoamericanos elegibles en alianza con organizaciones australianas',
    territorio: 'Argentina, Brasil, Chile, Colombia, Costa Rica, Cuba, Ecuador, El Salvador, Guatemala, México, Panamá, Perú y Uruguay',
    linea_tematica: 'Cooperación bilateral, comercio, educación y cultura',
    requisitos: 'Obligatorio contar con socio australiano que administre la subvención en dólares australianos',
    fuente_oficial: 'https://dfat.smartygrants.com.au/COALAR2026-27',
    informacion_faltante: 'Detalle de líneas temáticas específicas por convocatoria anual',
    tipo_financiador: 'cooperacion_bilateral',
    ambito: 'internacional',
  },
  {
    nombre: 'Transforma Territorio 2026 - Región Litoral',
    entidad: 'Ministerio de Industria, Energía y Minería (Dinapyme) y Comisión Técnica Mixta de Salto Grande, Uruguay',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-09-21',
    fecha_cierre: '2026-09-21',
    monto: 'Hasta UYU 150.000 por proyecto, hasta el 80% del costo; bolsa regional de UYU 2.500.000',
    beneficiarios: 'Micro y pequeñas empresas industriales, artesanales y de servicios; unidades de producción familiar agropecuaria',
    territorio: 'Uruguay (Artigas, Salto, Paysandú y Río Negro)',
    linea_tematica: 'Desarrollo productivo territorial',
    requisitos: 'Contrapartida mínima del 20%; registro ante DGI, Certificado PYME o de productor familiar; ejecución en hasta ocho meses',
    fuente_oficial: 'https://www.gub.uy/ministerio-industria-energia-mineria/comunicacion/convocatorias/transforma-territorio-2026',
    tipo_financiador: 'estado_nacional',
    ambito: 'nacional',
  },
  {
    nombre: 'Sistemas de Cuidado Local en Portoviejo y Cuenca (UNW-AC-ECU-CFP-2026-005)',
    entidad: 'ONU Mujeres, Oficina de Ecuador',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-09-23',
    fecha_cierre: '2026-09-23',
    monto: 'No especificado en la fuente',
    beneficiarios: 'Organizaciones de la sociedad civil constituidas, con experiencia en género y cuidados; se alienta a organizaciones de mujeres',
    territorio: 'Ecuador',
    linea_tematica: 'Igualdad de género y economía del cuidado',
    requisitos: 'Propuesta técnica y financiera con marco lógico, presupuesto, matriz de riesgos, hojas de vida y carta de alianza',
    fuente_oficial: 'https://lac.unwomen.org/es/programme-implementation/2026/09/sistemas-de-cuidado-local',
    tipo_financiador: 'onu',
    ambito: 'nacional',
  },
  {
    nombre: 'Tejiendo Vida para las Áreas Protegidas 2026 (quinta convocatoria)',
    entidad: 'Corporación Autónoma Regional de las Cuencas de los Ríos Negro y Nare (Cornare)',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-09-27',
    fecha_cierre: '2026-09-27',
    monto: 'COP 900 millones en total; COP 30 millones por proyecto para 30 iniciativas',
    beneficiarios: 'Organizaciones comunitarias que desarrollan actividades en las áreas protegidas de la jurisdicción de Cornare',
    territorio: 'Colombia (Oriente antioqueño)',
    linea_tematica: 'Ambiente y conservación',
    requisitos: 'Contrapartida comunitaria del 30% en dinero o mano de obra; ubicación en áreas protegidas de Cornare; formulario de intención',
    fuente_oficial: 'https://www.cornare.gov.co/informacion-de-interes/lineamientos-tejiendo-vida-para-las-areas',
    tipo_financiador: 'estado_local',
    ambito: 'departamental',
  },
  {
    nombre: 'IBRO Seeding Neuroscience Grants',
    entidad: 'International Brain Research Organization (IBRO)',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-09-30',
    fecha_cierre: '2026-09-30',
    monto: 'Hasta USD 4.000 para América Latina',
    beneficiarios: 'Grupos de neurocientíficos u organizaciones que trabajan en constituir sociedades o redes que aún no existen formalmente',
    territorio: 'África, Asia-Pacífico y América Latina',
    linea_tematica: 'Ciencia y neurociencia',
    requisitos: 'Al menos una carta de apoyo de líderes o instituciones reconocidas; plan accionable de constitución formal; se excluyen congresos aislados',
    fuente_oficial: 'https://ibro.org/grant/seeding-neuroscience-grants/',
    tipo_financiador: 'ong',
    ambito: 'internacional',
  },
  {
    nombre: '2026 OAE Research Call for Proposals',
    entidad: 'Carbon to Sea Initiative',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-09-30',
    fecha_cierre: '2026-09-30',
    monto: 'Hasta USD 6 millones en total: USD 5 millones para la red de campo y USD 1 millón para investigación dirigida',
    beneficiarios: 'Equipos científicos y de ingeniería y organizaciones de investigación',
    territorio: 'Participación global; bases traducidas al español y al portugués',
    linea_tematica: 'Investigación oceánica y clima',
    requisitos: 'Presentación de pre-propuesta antes del cierre; la convocatoria invita expresamente a la participación global',
    fuente_oficial: 'https://www.carbontosea.org/2026-oae-research-call-for-proposals/',
    tipo_financiador: 'ong',
    ambito: 'internacional',
  },
  {
    nombre: 'Japan World Exposition 1970 Commemorative Fund (JEC Fund), subvenciones 2027',
    entidad: 'Osaka 21st Century Association',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-09-30',
    fecha_cierre: '2026-09-30',
    monto: 'Hasta JPY 5.000.000 por proyecto; presupuesto total aproximado de JPY 135.000.000',
    beneficiarios: 'Gobiernos nacionales y locales extranjeros y organizaciones sin ánimo de lucro de interés público',
    territorio: 'Abierta a organizaciones de cualquier país, incluida América Latina',
    linea_tematica: 'Intercambio cultural, educación, bienestar social y ambiente',
    requisitos: 'Formulario oficial dentro del periodo de aplicaciones del 1 al 30 de septiembre de 2026; el proyecto debe ser internacional y de interés público',
    fuente_oficial: 'https://www.osaka21.or.jp/jecfund/english/information/',
    tipo_financiador: 'filantropia_privada',
    ambito: 'internacional',
  },
  {
    nombre: 'Ayuda a la programación musical 2026',
    entidad: 'Programa de Fomento de las Músicas Iberoamericanas (Ibermúsicas)',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-01',
    fecha_cierre: '2026-10-01',
    monto: 'Hasta USD 10.000 (EUR 10.000 para España y Portugal)',
    beneficiarios: 'Festivales, ferias, mercados, salas de concierto, instituciones culturales, universidades y otras entidades inscritas en el Catálogo Ibermúsicas',
    territorio: 'Argentina, Brasil, Chile, Colombia, Costa Rica, Cuba, Ecuador, España, México, Panamá, Paraguay, Perú, Portugal, Uruguay y Venezuela',
    linea_tematica: 'Cultura y música',
    requisitos: 'Inscripción previa en el Catálogo Ibermúsicas; actividades entre el 1 de enero y el 31 de diciembre de 2027; cierre a las 23:59 hora local',
    fuente_oficial: 'https://www.ibermusicas.org/index.php/convocatorias/',
    tipo_financiador: 'cooperacion_multilateral',
    ambito: 'regional',
  },
  {
    nombre: 'Ayuda a instituciones para residencias 2026',
    entidad: 'Programa de Fomento de las Músicas Iberoamericanas (Ibermúsicas)',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-01',
    fecha_cierre: '2026-10-01',
    monto: 'Hasta USD 5.000 (EUR 5.000 para España y Portugal)',
    beneficiarios: 'Instituciones, organismos y agrupaciones artísticas públicas o privadas',
    territorio: 'Brasil, Chile, Colombia, Costa Rica, Cuba, El Salvador, España, México, Panamá, Paraguay, Perú y Portugal',
    linea_tematica: 'Cultura y música',
    requisitos: 'La persona invitada no puede residir en su país de origen ni en el país anfitrión; residencia mínima de tres semanas; resultados el 27 de noviembre de 2026',
    fuente_oficial: 'https://www.ibermusicas.org/index.php/convocatorias/',
    tipo_financiador: 'cooperacion_multilateral',
    ambito: 'regional',
  },
  {
    nombre: 'Ayuda a la promoción del repertorio iberoamericano 2026',
    entidad: 'Programa de Fomento de las Músicas Iberoamericanas (Ibermúsicas)',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-01',
    fecha_cierre: '2026-10-01',
    monto: 'Hasta USD 2.500 (EUR 2.500 para España y Portugal)',
    beneficiarios: 'Orquestas, coros, ensambles, solistas y otras formaciones musicales inscritas en el registro de Ibermúsicas',
    territorio: 'Brasil, Chile, Colombia, Cuba, Ecuador, México, Panamá, Paraguay, Perú o Portugal',
    linea_tematica: 'Cultura y música',
    requisitos: 'La obra debe pertenecer a un país distinto al de la formación postulante; actividades durante 2027; cierre a las 23:59',
    fuente_oficial: 'https://www.ibermusicas.org/index.php/convocatorias/',
    tipo_financiador: 'cooperacion_multilateral',
    ambito: 'regional',
  },
  {
    nombre: 'Protected or Conserved Area Creation Awards y Feasibility Awards',
    entidad: 'Rainforest Trust',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-01',
    fecha_cierre: '2026-10-01',
    monto: 'Feasibility Awards alrededor de USD 10.000; Creation Awards sin monto máximo establecido',
    beneficiarios: 'ONG legalmente registradas y autorizadas para operar en el país del proyecto',
    territorio: 'Trópicos y subtrópicos a nivel global, incluida Sudamérica',
    linea_tematica: 'Conservación de biodiversidad y áreas protegidas',
    requisitos: 'Aval gubernamental y consentimiento de pueblos indígenas y comunidades; propuestas de USD 250.000 o más exigen nota conceptual cuatro meses antes',
    fuente_oficial: 'https://www.rainforesttrust.org/get-involved/apply-for-funding/',
    tipo_financiador: 'ong',
    ambito: 'internacional',
  },
  {
    nombre: 'Blue Catalyst Fund',
    entidad: 'Fair Carbon y Finance Earth',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-01',
    fecha_cierre: '2026-10-01',
    monto: 'USD 85.000 a 100.000 en prefactibilidad y USD 480.000 a 520.000 en posfactibilidad (cerca del 35% en efectivo)',
    beneficiarios: 'Organizaciones que desarrollan proyectos de conservación o restauración de manglares',
    territorio: 'Global, excluyendo jurisdicciones sancionadas por el GAFI o con alerta de viaje nivel 4',
    linea_tematica: 'Ambiente, carbono azul y restauración de manglares',
    requisitos: 'Umbrales mínimos de escala: 1.000 hectáreas para restauración, 5.000 para conservación o 1 millón de VCU',
    fuente_oficial: 'https://www.faircarbon.org/blue-catalyst-fund',
    tipo_financiador: 'filantropia_privada',
    ambito: 'internacional',
  },
  {
    nombre: 'Project Funding (Projektförderung)',
    entidad: 'Ernst von Siemens Musikstiftung',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-01',
    fecha_cierre: '2026-10-01',
    monto: 'Sin máximo definido; la subvención no debería superar un tercio del costo total del proyecto',
    beneficiarios: 'Únicamente instituciones organizadoras del proyecto; no se aceptan postulaciones individuales',
    territorio: 'No especificado en la fuente',
    linea_tematica: 'Cultura y música contemporánea',
    requisitos: 'Plazo del 1 de octubre a las 14:00 CEST para proyectos que inicien el año siguiente; postulación en línea en alemán o inglés',
    fuente_oficial: 'https://evs-musikstiftung.ch/en/project-funding/application/',
    tipo_financiador: 'filantropia_privada',
    ambito: 'internacional',
  },
  {
    nombre: 'Request for Proposals: Launchpad Funds',
    entidad: 'Coefficient Giving',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-02',
    fecha_cierre: '2026-10-02',
    monto: 'Pre-semilla USD 200.000 a 10 millones; semilla y escalamiento USD 10 a más de 50 millones',
    beneficiarios: 'Personas, fondos nuevos o existentes, y organizaciones implementadoras; también universidades e institutos de investigación',
    territorio: 'Sin restricción geográfica declarada',
    linea_tematica: 'Salud global y bienestar',
    requisitos: 'Expresión de interés en línea describiendo el fondo propuesto, el problema abordado y el gerente general responsable',
    fuente_oficial: 'https://coefficientgiving.org/funds/global-health-wellbeing-opportunities/request-for-proposals',
    tipo_financiador: 'filantropia_privada',
    ambito: 'internacional',
  },
  {
    nombre: 'Fondo de Juventud y Acción Climática 2026, Bogotá',
    entidad: 'Alcaldía Mayor de Bogotá y Bloomberg Philanthropies',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-04',
    fecha_cierre: '2026-10-04',
    monto: 'Hasta USD 3.000 por iniciativa; bolsa total de USD 40.000',
    beneficiarios: 'Equipos liderados por al menos tres jóvenes de 15 a 24 años, con respaldo de una organización elegible',
    territorio: 'Colombia (Bogotá)',
    linea_tematica: 'Clima y acción ambiental',
    requisitos: 'Respaldo de organización juvenil, entidad que trabaje con jóvenes o institución educativa; propuesta alineada con la política distrital',
    fuente_oficial: 'https://bogota.gov.co/internacional/bogota-abre-convocatoria-para-impulsar-iniciativas-de-a',
    tipo_financiador: 'estado_local',
    ambito: 'municipal',
  },
  {
    nombre: 'Catalyst Grant 2026: Agentic Workflows You Can Trust',
    entidad: 'Digital Science',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-05',
    fecha_cierre: '2026-10-05',
    monto: 'Hasta GBP 25.000 por proyecto, sin cesión de participación accionaria',
    beneficiarios: 'Personas, startups en etapa temprana, equipos de investigación y fundadores; no se exige producto terminado',
    territorio: 'Convocatoria global, sin restricciones geográficas',
    linea_tematica: 'Inteligencia artificial aplicada a la investigación',
    requisitos: 'Postulación en línea antes de las 17:00 BST explicando el problema, el enfoque agéntico y el estado del desarrollo',
    fuente_oficial: 'https://www.digital-science.com/about-us/investment/catalyst-grant/',
    tipo_financiador: 'empresa_privada',
    ambito: 'internacional',
  },
  {
    nombre: 'Fourth Global Innovation Challenge: Preparing Youth for AI',
    entidad: 'Citi Foundation',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-06',
    fecha_cierre: '2026-10-06',
    monto: 'USD 500.000 por organización; USD 25 millones en total para unas 50 organizaciones, en 24 meses',
    beneficiarios: 'Organizaciones sin ánimo de lucro registradas, con estados financieros auditados externamente',
    territorio: 'Colombia, Ecuador, Perú, Argentina, Brasil, Chile, Costa Rica, Guatemala, Honduras, México, Panamá, Paraguay, Uruguay y otros',
    linea_tematica: 'Empleabilidad juvenil e inteligencia artificial',
    requisitos: 'Carta de intención antes de las 12:00 hora de Nueva York; no se admite patrocinador fiscal; operar en al menos un país elegible',
    fuente_oficial: 'https://www.citigroup.com/global/foundation/programs/global-innovation-challenge',
    tipo_financiador: 'filantropia_corporativa',
    ambito: 'regional',
  },
  {
    nombre: 'AI and Teen Development Research Grant Program',
    entidad: 'OpenAI Group PBC',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-06',
    fecha_cierre: '2026-10-06',
    monto: 'Hasta USD 1.000.000 por subvención; USD 5.000.000 en total para el programa',
    beneficiarios: 'Personas mayores de 18 años vinculadas a instituciones o organizaciones de investigación',
    territorio: 'Abierta a propuestas de cualquier país, con prioridad en países con adopción significativa de IA',
    linea_tematica: 'Investigación, inteligencia artificial y adolescencia',
    requisitos: 'Vinculación institucional o experiencia sustantiva en desarrollo adolescente, bienestar o impactos de la IA; postulación vía SM Apply',
    fuente_oficial: 'https://openai.com/index/teen-development-research-grants/',
    tipo_financiador: 'empresa_privada',
    ambito: 'internacional',
  },
  {
    nombre: 'Fondo Ingenia, edición 2027',
    entidad: 'Fundación Ciudad del Saber (Panamá)',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-09',
    fecha_cierre: '2026-10-09',
    monto: 'Hasta PAB 20.000 por proyecto seleccionado',
    beneficiarios: 'Organizaciones privadas sin fines de lucro constituidas en Panamá, con 5 años de existencia legal y 3 de actividad demostrada',
    territorio: 'Panamá',
    linea_tematica: 'Educación, cultura y derechos culturales',
    requisitos: 'Contrapartida mínima del 25% en efectivo o en especie; duración de 12 a 18 meses; postulación en dos fases',
    fuente_oficial: 'https://ciudaddelsaber.org/fondo-ingenia/',
    tipo_financiador: 'ong',
    ambito: 'nacional',
  },
  {
    nombre: 'Fondo Concursable para Sitios de Memoria 2026',
    entidad: 'Intendencia de Montevideo (Uruguay)',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-09',
    fecha_cierre: '2026-10-09',
    monto: 'UYU 800.000 en total, para financiar hasta 10 proyectos',
    beneficiarios: 'Comisiones de gestión de Sitios de Memoria, asociaciones civiles y fundaciones sin fines de lucro, organizaciones sociales e instituciones educativas',
    territorio: 'Uruguay (Montevideo)',
    linea_tematica: 'Derechos humanos, memoria y cultura',
    requisitos: 'El Sitio de Memoria debe integrar la Red departamental de Sitios de Memoria de Montevideo al momento de postular',
    fuente_oficial: 'https://montevideo.gub.uy/tipo/area-tematica/inclusion-social/derechos-humanos/fondo-concursable',
    tipo_financiador: 'estado_local',
    ambito: 'municipal',
  },
  {
    nombre: 'Convocatoria de CTeI para la Atención de Desafíos en Salud Derivados de la Situación de Desastre (001 de 2026)',
    entidad: 'Ministerio de Ciencia, Tecnología e Innovación de Colombia (Minciencias)',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-13',
    fecha_cierre: '2026-10-13',
    monto: 'COP 109.000 millones para el total de la convocatoria; monto por proyecto no especificado en la fuente',
    beneficiarios: 'Entidades ejecutoras domiciliadas en Colombia: centros de investigación y desarrollo tecnológico, IES, empresas y actores del SNCTI',
    territorio: 'Colombia',
    linea_tematica: 'Salud, ciencia, tecnología e innovación',
    requisitos: 'Cuatro líneas temáticas: salud mental y rehabilitación, enfermedades transmisibles en albergues, enfermedades no transmisibles y cáncer, y salud ambiental; cierre a las 5:00 p. m.',
    fuente_oficial: 'https://minciencias.gov.co/convocatorias/convocatoria-ctei-para-la-atencion-desafios-en-sal',
    tipo_financiador: 'estado_nacional',
    ambito: 'nacional',
  },
  {
    nombre: 'Concurso del Fondo de Protección Ambiental (FPA) 2027',
    entidad: 'Ministerio del Medio Ambiente de Chile',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-14',
    fecha_cierre: '2026-10-14',
    monto: 'Hasta CLP 6.000.000 por proyecto',
    beneficiarios: 'Entidades privadas sin fines de lucro, centros de padres de establecimientos educacionales y comunidades y asociaciones indígenas reconocidas por CONADI',
    territorio: 'Chile',
    linea_tematica: 'Ambiente, biodiversidad y economía circular',
    requisitos: 'Postulación en línea en fondos.mma.gob.cl según las bases de la línea correspondiente',
    fuente_oficial: 'https://mma.gob.cl/ministerio-del-medio-ambiente-abre-postulaciones-del-fondo-de-proteccion',
    tipo_financiador: 'estado_nacional',
    ambito: 'nacional',
  },
  {
    nombre: 'Mohamed bin Zayed Species Conservation Fund, ventana de octubre 2026',
    entidad: 'The Mohamed bin Zayed Species Conservation Fund',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-15',
    fecha_cierre: '2026-10-15',
    monto: 'No especificado en la fuente',
    beneficiarios: 'Organizaciones y personas directamente involucradas en la conservación de especies',
    territorio: 'Global, sin discriminación por región ni por especie',
    linea_tematica: 'Conservación de especies y biodiversidad',
    requisitos: 'Prioriza proyectos de especie única; permite salarios y viáticos ligados al proyecto pero no gastos administrativos generales; postulación en inglés',
    fuente_oficial: 'https://www.speciesconservation.org/biodiversity-nature-people/conservation-philanthropy/grants',
    tipo_financiador: 'filantropia_privada',
    ambito: 'internacional',
  },
  {
    nombre: 'AMBSO Impact Research Initiative',
    entidad: 'AMBSO',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-16',
    fecha_cierre: '2026-10-16',
    monto: 'Hasta USD 10.000 por proyecto',
    beneficiarios: 'Investigadores individuales, instituciones académicas, organizaciones de investigación y equipos de investigación',
    territorio: 'Mundial, América Latina incluida',
    linea_tematica: 'Salud e investigación aplicada',
    requisitos: 'No son elegibles entidades con ánimo de lucro, organizaciones políticas ni grupos de cabildeo; presentación mediante expresión de interés',
    fuente_oficial: 'https://www.ambso.org/opportunities/grants/call-for-expression-of-interest-eoi-ambso-impact',
    tipo_financiador: 'ong',
    ambito: 'internacional',
  },
  {
    nombre: 'Coral Accelerator Program (CAP) 2026',
    entidad: 'CORDAP, Coral Research & Development Accelerator Platform (G20)',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-19',
    fecha_cierre: '2026-10-19',
    monto: 'Hasta USD 1.000.000 por proyecto; asignación total de USD 3,2 millones',
    beneficiarios: 'Organizaciones sin y con fines de lucro, universidades, institutos de investigación y organismos gubernamentales',
    territorio: 'Global, con requisito explícito de incluir al menos una organización de país de ingreso bajo o medio',
    linea_tematica: 'Conservación marina y tecnología de arrecifes',
    requisitos: 'Consorcio de mínimo 3 solicitantes de al menos 2 países; nota conceptual hasta las 18:00 UTC; duración de 12 a 36 meses',
    fuente_oficial: 'https://cordap.org/awards/',
    tipo_financiador: 'cooperacion_multilateral',
    ambito: 'internacional',
  },
  {
    nombre: 'Programa Distrital de Apoyos Concertados (PDAC) 2027',
    entidad: 'Secretaría Distrital de Cultura, Recreación y Deporte e Idartes, Bogotá',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-22',
    fecha_cierre: '2026-10-22',
    monto: 'Hasta el 70% del costo total del proyecto; la organización aporta el 30% restante',
    beneficiarios: 'Entidades sin ánimo de lucro constituidas en Colombia, con sede o sucursal en Bogotá D.C. y trayectoria comprobada',
    territorio: 'Colombia (Bogotá D.C.)',
    linea_tematica: 'Cultura, arte y patrimonio',
    requisitos: 'Vigencia legal que supere la ejecución más 3 años, registro activo en SECOP II e inscripción en la plataforma CULTURED; cierre a las 5:00 p. m.',
    fuente_oficial: 'https://www.idartes.gov.co/es/noticias/ya-estan-abiertas-las-convocatorias-para-el-pdac-2027',
    tipo_financiador: 'estado_local',
    ambito: 'municipal',
  },
  {
    nombre: '8th Call for Proposals for Small-Size Grants',
    entidad: 'Global EbA Fund, con secretariado de UICN y PNUMA',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-26',
    fecha_cierre: '2026-10-26',
    monto: 'Hasta USD 250.000 por proyecto, ejecución máxima de 24 meses',
    beneficiarios: 'ONG e INGO, organismos intergubernamentales, organizaciones comunitarias e indígenas, universidades, institutos de investigación y consorcios',
    territorio: 'Países elegibles para AOD, con prioridad en pequeños Estados insulares y países menos adelantados',
    linea_tematica: 'Cambio climático y adaptación basada en ecosistemas',
    requisitos: 'Ventana de postulación del 28 de septiembre al 26 de octubre de 2026; no se financia directamente a gobiernos, consorcios con agencia líder',
    fuente_oficial: 'https://globalebafund.org/small-size-grants/',
    tipo_financiador: 'onu',
    ambito: 'internacional',
  },
  {
    nombre: 'Convocatoria de Proyectos de Investigación vigencia 2026-2027',
    entidad: 'ASFACOP, en alianza con ASEPUC Red Latinoamérica y ALAFEC',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-30',
    fecha_cierre: '2026-10-30',
    monto: 'No especificado en la fuente',
    beneficiarios: 'Investigadores adscritos a grupos de investigación avalados por universidades afiliadas a ASFACOP',
    territorio: 'Colombia, España y países de América Latina',
    linea_tematica: 'Investigación aplicada, contabilidad social y sostenibilidad',
    requisitos: 'Aval institucional de las universidades participantes; no se admiten investigadores independientes ni instituciones no afiliadas',
    fuente_oficial: 'https://asfacop.org.co/proyectos-de-investigacion-vigencia-2026-2027/',
    tipo_financiador: 'academia',
    ambito: 'regional',
  },
  {
    nombre: '29.ª Convocatoria del Fondo Regional para la Cooperación Triangular con América Latina y el Caribe',
    entidad: 'Ministerio Federal de Cooperación Económica y Desarrollo de Alemania (BMZ), implementado por la GIZ',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierre interno en Colombia el 7 de octubre',
    fecha_cierre: '2026-10-31',
    monto: 'Hasta EUR 300.000 por proyecto como aporte no reembolsable',
    beneficiarios: 'Instituciones públicas nacionales y subnacionales, sector privado, organizaciones filantrópicas, sociedad civil y academia',
    territorio: 'América Latina y el Caribe; al menos un socio de México, Brasil, Colombia, Ecuador, Bolivia o Perú',
    linea_tematica: 'Cooperación internacional al desarrollo',
    requisitos: 'Estructura de tres socios, ejecución máxima de dos años; cartas de aval de las entidades rectoras vía Embajadas de Alemania',
    fuente_oficial: 'https://fondo-cooperacion-triangular.net/convocatorias-de-proyecto/',
    tipo_financiador: 'cooperacion_bilateral',
    ambito: 'regional',
  },
  {
    nombre: 'AI for Science and Safety Nodes RFP: Local Compute',
    entidad: 'Foresight Institute',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-31',
    fecha_cierre: '2026-10-31',
    monto: 'USD 30.000 a 100.000 por proyecto',
    beneficiarios: 'Organizaciones sin ánimo de lucro y con ánimo de lucro; estas últimas deben justificar por qué requieren subvención',
    territorio: 'Sin restricción geográfica declarada',
    linea_tematica: 'Ciencia abierta e inteligencia artificial',
    requisitos: 'Todos los productos financiados deben liberarse como código abierto; hasta 10% de los costos directos para gastos generales; reportes periódicos',
    fuente_oficial: 'https://foresight.org/grants/ai-science-safety-nodes-rfp-local-compute/',
    tipo_financiador: 'ong',
    ambito: 'internacional',
  },
  {
    nombre: 'AI for Science and Safety Nodes RFP: Coordination and Accountability',
    entidad: 'Foresight Institute',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-10-31',
    fecha_cierre: '2026-10-31',
    monto: 'USD 30.000 a 100.000 por proyecto',
    beneficiarios: 'Personas, equipos de investigación y organizaciones con y sin ánimo de lucro',
    territorio: 'Global; la convocatoria no establece restricciones geográficas',
    linea_tematica: 'Inteligencia artificial, ciencia y seguridad',
    requisitos: 'Resultados de código abierto con hitos alcanzables entre uno y tres años; cierre a las 23:59 PDT',
    fuente_oficial: 'https://foresight.org/grants/ai-science-safety-nodes-rfp-coordination-and-accountability/',
    tipo_financiador: 'ong',
    ambito: 'internacional',
  },
  {
    nombre: 'Community Impact Grant Program 2026',
    entidad: 'TEEEM Foundation',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-11-01',
    fecha_cierre: '2026-11-01',
    monto: 'USD 5.000 a 30.000 en tres niveles: Community, Growth y Transformational',
    beneficiarios: 'Organizaciones sin ánimo de lucro y entidades benéficas con liderazgo sólido y capacidad institucional comprobable',
    territorio: 'Abierta a organizaciones de cualquier país, sin restricción geográfica declarada',
    linea_tematica: 'Desarrollo comunitario, educación y emprendimiento social',
    requisitos: 'Ventana de postulación del 17 de agosto al 1 de noviembre de 2026; demostrar soluciones centradas en la comunidad e impacto sostenible',
    fuente_oficial: 'https://www.teeem.org/foundation',
    tipo_financiador: 'filantropia_privada',
    ambito: 'internacional',
  },
  {
    nombre: 'Rapid Fund (Fondo Rápido para proyectos Wikimedia)',
    entidad: 'Wikimedia Foundation',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-11-01',
    fecha_cierre: '2026-11-01',
    monto: 'USD 500 a 5.000 por proyecto, con máximo de USD 10.000 anuales por postulante',
    beneficiarios: 'Personas, grupos, afiliados Wikimedia y organizaciones que cumplan los requisitos de elegibilidad',
    territorio: 'Abierta a solicitantes de todo el mundo',
    linea_tematica: 'Conocimiento abierto, cultura digital y educación',
    requisitos: 'Experiencia relevante en el proyecto Wikimedia objetivo; duración de 1 a 12 meses; debe referirse a trabajo futuro planificado',
    fuente_oficial: 'https://meta.wikimedia.org/wiki/Grants:Project/Rapid',
    tipo_financiador: 'filantropia_privada',
    ambito: 'internacional',
  },
  {
    nombre: 'Restack, convocatoria abierta de subvenciones, ciclo de noviembre 2026',
    entidad: 'NLnet Foundation (consorcio Restack)',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-11-03',
    fecha_cierre: '2026-11-03',
    monto: 'EUR 5.000 a 50.000 en la primera propuesta; hasta EUR 150.000 en posteriores; fondo total de EUR 7 millones',
    beneficiarios: 'Personas y organizaciones con y sin ánimo de lucro, no se exige afiliación universitaria ni personería jurídica formal',
    territorio: 'Abierta a postulantes de cualquier país; el proyecto debe tener dimensión europea',
    linea_tematica: 'Tecnología abierta e infraestructura digital',
    requisitos: 'Propuesta en nlnet.nl/propose antes de las 12:00 CET; resultados científicos en acceso abierto y software bajo licencia libre',
    fuente_oficial: 'https://nlnet.nl/restack/',
    tipo_financiador: 'filantropia_privada',
    ambito: 'internacional',
  },
  {
    nombre: 'Local Impact Mini Grants',
    entidad: 'Interledger Foundation',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-11-11',
    fecha_cierre: '2026-11-11',
    monto: 'USD 500 a 3.000 por iniciativa',
    beneficiarios: 'Organizaciones comunitarias, entidades sin ánimo de lucro, cooperativas, startups fintech locales y empresas sociales; se aceptan entidades no registradas',
    territorio: 'Abierta a cualquier país, con prioridad para el Sur Global; excluye países sancionados por OFAC',
    linea_tematica: 'Inclusión financiera digital',
    requisitos: 'Revisión continua de solicitudes; se exige plan de proyecto concreto y relación directa con la comunidad beneficiaria',
    fuente_oficial: 'https://interledger.org/grant/local-impact-grant/',
    tipo_financiador: 'filantropia_privada',
    ambito: 'internacional',
  },
  {
    nombre: 'Science for Peace and Security (SPS) Call for Proposals 2027-1',
    entidad: 'Programa Ciencia para la Paz y la Seguridad (SPS) de la OTAN',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-11-15',
    fecha_cierre: '2026-11-15',
    monto: 'Sin tope fijo; los proyectos de 36 meses se sitúan típicamente en torno a EUR 400.000',
    beneficiarios: 'Instituciones gubernamentales, académicas y sin ánimo de lucro; las empresas con ánimo de lucro no son elegibles',
    territorio: 'Países miembros de la OTAN y países socios; Colombia es el único país latinoamericano en la lista',
    linea_tematica: 'Ciencia, tecnología y seguridad',
    requisitos: 'Propuesta completa antes de las 23:59 CET; participación obligatoria de instituciones de país OTAN y de país socio',
    fuente_oficial: 'https://www.nato.int/content/dam/nato/webready/documents/sps/grants/SPS-Call4proposals',
    tipo_financiador: 'cooperacion_multilateral',
    ambito: 'internacional',
  },
  {
    nombre: 'Medium-Size Grants Call for Proposals',
    entidad: 'Global EbA Fund, con secretariado de UICN y PNUMA',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-11-16',
    fecha_cierre: '2026-11-16',
    monto: 'Hasta USD 500.000 por subvención',
    beneficiarios: 'ONG e INGO, organismos intergubernamentales, organizaciones comunitarias e indígenas, universidades y consorcios con solicitante líder',
    territorio: 'Países elegibles para AOD, o iniciativas globales y temáticas',
    linea_tematica: 'Cambio climático y adaptación basada en ecosistemas',
    requisitos: 'Ventana de postulación del 12 de octubre al 16 de noviembre de 2026; no se financian intervenciones aisladas ni gobiernos de forma directa',
    fuente_oficial: 'https://globalebafund.org/medium-size-grants/',
    tipo_financiador: 'onu',
    ambito: 'internacional',
  },
  {
    nombre: 'Climate Intervention Environmental Impact Fund (CIEIF), programa de subvenciones',
    entidad: 'Climate Intervention Environmental Impact Fund, administrado por Social and Environmental Entrepreneurs',
    tipo: 'abierta actualmente',
    estado_convocatoria: 'Abierta, cierra 2026-12-01',
    fecha_cierre: '2026-12-01',
    monto: 'USD 75.000 por subvención, en tres desembolsos atados a hitos; tres subvenciones disponibles',
    beneficiarios: 'Entidades que realizan pruebas de campo de tecnologías de intervención climática',
    territorio: 'No especificado en la fuente',
    linea_tematica: 'Clima y evaluación de impacto ambiental',
    requisitos: 'Describir la naturaleza jurídica de la entidad y aportar sitio web institucional; un tercio del monto se libera a la aprobación',
    fuente_oficial: 'https://cieif.org/',
    tipo_financiador: 'filantropia_privada',
    ambito: 'internacional',
  },
  {
    nombre: 'Convocatoria permanente de propuestas del Fondo de Innovación para el Desarrollo (FID)',
    entidad: 'Fund for Innovation in Development, alojado en la Agence Française de Développement',
    tipo: 'permanente',
    estado_convocatoria: 'Ventanilla abierta todo el año',
    fecha_cierre: 'Ventanilla abierta',
    monto: 'Etapa 1 hasta EUR 200.000; Etapa 2 hasta EUR 1.500.000; Etapa 3 hasta EUR 4.000.000',
    beneficiarios: 'ONG, empresas, universidades y entidades públicas, de forma independiente o en consorcio; no se admiten postulaciones individuales',
    territorio: 'Países de ingreso bajo y medio elegibles para AOD, incluidos Colombia, Perú y Ecuador',
    linea_tematica: 'Innovación para el desarrollo (multisectorial)',
    requisitos: 'Postulación en línea permanente con nota conceptual; el proyecto debe demostrar evidencia de impacto y ruta de escalamiento',
    fuente_oficial: 'https://fundinnovation.dev/en/launch-project',
    tipo_financiador: 'cooperacion_bilateral',
    ambito: 'internacional',
  },
  {
    nombre: 'Development Innovation Ventures (DIV Fund)',
    entidad: 'DIV Fund',
    tipo: 'permanente',
    estado_convocatoria: 'Ventanilla abierta todo el año',
    fecha_cierre: 'Ventanilla abierta',
    monto: 'Etapa 1 hasta USD 200.000; Etapa 2 hasta USD 500.000; Etapa 3 hasta USD 1,5 millones',
    beneficiarios: 'Organizaciones sin ánimo de lucro, empresas, startups, empresas privadas y institutos de investigación',
    territorio: 'Países de ingreso bajo, medio-bajo y medio-alto según la clasificación del Banco Mundial',
    linea_tematica: 'Innovación, tecnología y desarrollo',
    requisitos: 'Recepción rodante durante el año; el proyecto debe estar más allá del prototipo y con pruebas en condiciones reales; no elegibles personas naturales ni agencias gubernamentales',
    fuente_oficial: 'https://www.div.fund/apply',
    tipo_financiador: 'cooperacion_bilateral',
    ambito: 'internacional',
  },
]

async function ejecutarSiembra() {
  const mapaGuardadas = await guardarEnBiblioteca(supabase, CONVOCATORIAS_PROPULSA)
  return {
    status: 200,
    body: {
      ok: true,
      convocatorias_en_el_boletin: CONVOCATORIAS_PROPULSA.length,
      convocatorias_guardadas: mapaGuardadas.size,
      fuente: 'Convocatorias-No-Reembolsables-Propulsa-2026-09-20.pdf (corte 20 sep 2026)',
    },
  }
}

// Se visita una sola vez desde el navegador, con sesión del equipo Serving
// iniciada: /api/centinela/sembrar-boletin-propulsa
export async function GET(req: NextRequest) {
  if (!(await motorAutorizado(req))) {
    return NextResponse.json({ error: 'No autorizado' }, { status: 401 })
  }

  const resultado = await ejecutarSiembra()
  return NextResponse.json(resultado.body, { status: resultado.status })
}
